/* ══════════════════════════════════════════════════════════
   LE DOMANDE DEL CONFRONTATORE
   Ogni voce ha un `pos`, che è la posizione grossa, e un
   `nodo`, che è la premessa da cui quella posizione discende.
   Il nodo è la parte che serve davvero: due filosofi che
   rispondono la stessa cosa partendo da nodi incompatibili
   sono il caso più istruttivo di tutti, e senza il campo
   `nodo` la pagina non saprebbe dirlo.

   Le stringhe nuove usano l'apice inverso invece
   dell'apostrofo. Quando fa da chiave va racchiuso fra
   parentesi quadre, altrimenti non è una chiave valida.
   ══════════════════════════════════════════════════════════ */

const DOMANDE=[
{
 k:'anima', q:'L\'anima sopravvive al corpo?',
 r:{
  'Platone':{a:'427-347 a.C.', pos:'Sì', f:'Il corpo è la tomba dell\'anima.',
   d:'L\'anima preesiste alla nascita e continua dopo la morte. Il corpo è un impedimento: la filosofia è un esercizio di morte, cioè di separazione.',
   nodo:'L\'anima è una sostanza a sé, che si trova nel corpo come un prigioniero in una cella.'},
  'Aristotele':{a:'384-322 a.C.', pos:'No', f:'L\'anima è la forma del corpo vivente.',
   d:'Chiedere se anima e corpo siano separabili è come chiedere se lo siano la cera e l\'impronta. Sciolto il composto, non resta l\'individuo.',
   nodo:'L\'anima non è una cosa ma una funzione: il modo in cui questo corpo è vivo.'},
  'Tommaso d\'Aquino':{a:'1225-1274', pos:'Sì', f:'Forma sostanziale, e insieme sussistente.',
   d:'Prende da Aristotele l\'anima come forma, ma osserva che l\'intendere non usa organi: perciò quell\'operazione, e con essa l\'anima, può sussistere separata. Separata però è incompleta, e attende il corpo.',
   nodo:'Un\'operazione che non dipende dalla materia prova un\'anima che non dipende dalla materia.'},
  'Cartesio':{a:'1596-1650', pos:'Sì', f:'Posso dubitare del corpo, non del pensiero.',
   d:'Ciò che posso concepire distintamente separato, è separato. Penso me stesso senza estensione: dunque sono una cosa pensante, e il corpo è altro da me.',
   nodo:'Ciò che si concepisce chiaramente separato può esistere separato: il criterio è nella mente, non nell\'esperienza.'},
  'Hume':{a:'1711-1776', pos:'No', f:'Entro in me stesso e non trovo mai me stesso.',
   d:'Trovo un caldo, un freddo, un dolore: mai l\'io che li avrebbe. Se non c\'è un io ora, non c\'è nulla che possa sopravvivere dopo.',
   nodo:'Vale solo ciò che si trova nell\'esperienza, e nell\'esperienza non si trova nessun soggetto.'},
  'Kant':{a:'1724-1804', pos:'Non si può sapere', f:'L\'io penso non è un oggetto che conosco.',
   d:'Che ogni rappresentazione sia mia è una condizione formale del conoscere. Ricavarne che io sia una sostanza semplice e immortale è un paralogismo: si scambia una funzione per una cosa.',
   nodo:'Si conosce solo ciò che può darsi nell\'esperienza, e l\'io non vi si dà mai come oggetto.'}
 }},
{
 k:'giustizia', q:'Che cos\'è la giustizia?',
 r:{
  'Platone':{a:'427-347 a.C.', pos:'Un ordine che non decidiamo noi', f:'Fare la propria parte e non impicciarsi delle altre.',
   d:'Nella città come nell\'anima, giustizia è l\'ordine in cui ogni parte fa il suo e comanda la migliore. Non è una convenzione: è una struttura, e si può sbagliare a stabilirla.',
   nodo:'C\'è un ordine giusto che esiste indipendentemente da ciò che gli uomini decidono.'},
  'Aristotele':{a:'384-322 a.C.', pos:'Un ordine che non decidiamo noi', f:'Ai pari cose pari, ai diversi cose diverse.',
   d:'La giustizia distributiva ripartisce onori e beni secondo il merito; quella correttiva ristabilisce l\'equilibrio rotto da un torto, senza guardare a chi sia stato. E c\'è l\'equità, che corregge la legge dove è troppo generale.',
   nodo:'Giustizia è proporzione: il difficile non è il principio, è stabilire secondo quale merito.'},
  'Hobbes':{a:'1588-1679', pos:'Una convenzione fra uomini', f:'Dove non c\'è potere comune, non c\'è ingiustizia.',
   d:'Prima del patto non esistono giusto e ingiusto: sono qualità del discorso, non degli uomini soli. Giusto è tenere i patti, e i patti valgono solo se c\'è una spada che li fa valere.',
   nodo:'La giustizia non precede il potere: nasce con esso.'},
  'Rousseau':{a:'1712-1778', pos:'Una convenzione fra uomini', f:'Obbedire alla legge che ci si è prescritti.',
   d:'La legge è giusta quando viene da tutti e si applica a tutti. Non è la volontà di tutti, che è la somma degli interessi privati: è quello che resta quando le differenze si compensano.',
   nodo:'Giusto è ciò che il corpo intero vuole per il corpo intero, e nessuno può volerlo per lui.'},
  'Kant':{a:'1724-1804', pos:'Una forma valida per chiunque', f:'Agisci come se la tua massima dovesse farsi legge.',
   d:'Una condotta è giusta se la sua regola può essere voluta da chiunque senza contraddirsi. Le persone vanno trattate sempre anche come fine, mai soltanto come mezzo.',
   nodo:'Il criterio è formale: non guarda alle conseguenze ma alla forma della regola.'},
  'Hegel':{a:'1770-1831', pos:'Un ordine storico concreto', f:'La libertà che ha preso corpo nelle istituzioni.',
   d:'Il dovere astratto di Kant non dice ancora nulla di che cosa fare: si riempie solo dentro una famiglia, una società, uno Stato concreti. Giustizia è quando quelle istituzioni sono all\'altezza della libertà.',
   nodo:'Nessun criterio astratto basta: il giusto si dà solo dentro una comunità storica determinata.'}
 }},
{
 k:'certezza', q:'Si può conoscere qualcosa con certezza?',
 r:{
  'Cartesio':{a:'1596-1650', pos:'Sì', f:'Penso, dunque sono.',
   d:'Dubito di tutto finché trovo qualcosa di cui non posso dubitare: che sto dubitando. Da quel punto fermo, e dal criterio di chiarezza che vi si legge, si ricostruisce il resto.',
   nodo:'La certezza si trova dentro, e da lì si esce verso il mondo.'},
  'Hume':{a:'1711-1776', pos:'No, non sui fatti', f:'Che domani sorga il sole non è necessario.',
   d:'Le verità certe riguardano relazioni fra idee e non dicono nulla del mondo. Tutto ciò che riguarda i fatti riposa sull\'abitudine: abbiamo visto mille volte, e ci aspettiamo la milleunesima. Non è una prova.',
   nodo:'La necessità non si vede mai: la mettiamo noi, per abitudine.'},
  'Kant':{a:'1724-1804', pos:'Solo entro l\'esperienza', f:'L\'oggetto si regola sul pensiero.',
   d:'Spazio, tempo e categorie sono le nostre condizioni: valgono necessariamente per tutto ciò che possiamo incontrare, perché siamo noi a metterle. Perciò ci sono verità necessarie sull\'esperienza, e nessuna sulla cosa in sé.',
   nodo:'Si può essere certi di ciò che noi stessi abbiamo messo nell\'oggetto — e di nient\'altro.'},
  'Hegel':{a:'1770-1831', pos:'Sì', f:'Il vero è l\'intero.',
   d:'Nessuna proposizione isolata è vera: lo diventa nel posto che occupa nel percorso. La certezza immediata del «questo, qui, ora» è la più povera di tutte, e si dissolve appena la si dice.',
   nodo:'La verità non è un punto di partenza ma un risultato, e comprende gli errori attraversati.'},
  'Nietzsche':{a:'1844-1900', pos:'No, non sui fatti', f:'Non ci sono fatti, solo interpretazioni.',
   d:'Le verità sono metafore di cui si è dimenticata l\'origine. La domanda seria non è se una cosa sia vera, ma perché si abbia tanto bisogno che lo sia, e a chi giovi.',
   nodo:'Dietro ogni pretesa di verità c\'è una volontà: la si può ricostruire storicamente.'}
 }},
{
 k:'stato', q:'A che serve lo Stato?',
 r:{
  'Aristotele':{a:'384-322 a.C.', pos:'È una comunità naturale', f:'Nasce per vivere, esiste per vivere bene.',
   d:'La polis non è un\'invenzione utile: viene prima dell\'individuo come il tutto viene prima della parte. Fuori di essa si è o bestie o dèi.',
   nodo:'La comunità politica è naturale: non va giustificata, va fatta bene.'},
  'Hobbes':{a:'1588-1679', pos:'È una costruzione volontaria', f:'Fuori, la vita è solitaria, misera, brutale e breve.',
   d:'Nello stato di natura ognuno ha diritto a tutto, e perciò nessuno ha nulla al sicuro. Si cede tutto il potere a un sovrano: assoluto, perché un potere diviso è già guerra civile.',
   nodo:'L\'individuo viene prima della comunità, e la comunità è un artificio che lo protegge.'},
  'Locke':{a:'1632-1704', pos:'È una costruzione volontaria', f:'Il potere è un mandato, e i mandati si revocano.',
   d:'Vita, libertà e proprietà esistono prima dello Stato, solo mal difese. Si entra nella società per tutelarle: dunque il potere è limitato a quello scopo, e tradendolo si scioglie.',
   nodo:'I diritti precedono lo Stato, e perciò lo misurano.'},
  'Rousseau':{a:'1712-1778', pos:'È una costruzione volontaria', f:'Ciascuno si dà a tutti e quindi a nessuno.',
   d:'Non si cede il potere a un terzo: lo si tiene tutti insieme. La sovranità sta nel popolo, non si aliena e non si rappresenta.',
   nodo:'La libertà non è assenza di legge ma coincidenza fra chi obbedisce e chi comanda.'},
  'Kant':{a:'1724-1804', pos:'È una costruzione volontaria', f:'Una costituzione buona anche per un popolo di diavoli.',
   d:'Lo Stato di diritto non chiede virtù: chiede un congegno in cui le spinte egoistiche si bilancino. Il compito non finisce dentro i confini: la pace fra Stati è un dovere.',
   nodo:'Le istituzioni devono funzionare a prescindere dalla bontà di chi le abita.'},
  'Hegel':{a:'1770-1831', pos:'È una comunità naturale', f:'Lo Stato non è la somma degli individui.',
   d:'L\'individuo isolato che stipula il patto non è mai esistito: si è figli, allievi e cittadini prima di poter scegliere. Lo Stato è il luogo dove la libertà smette di essere un\'idea.',
   nodo:'Non c\'è nessuno stato di natura: si è sempre già dentro istituzioni che ci hanno formati.'}
 }}
,
{
 k:`dio`, q:`Si può dimostrare che Dio esiste?`,
 r:{
  [`Anselmo`]:{a:`1033-1109`, pos:`Sì, col solo pensiero`, f:`Ciò di cui non si può pensare il maggiore.`,
   d:`Anche chi nega capisce l'espressione, dunque ce l'ha nella mente. Ma se stesse solo nella mente se ne potrebbe pensare uno maggiore, quello che esiste anche fuori: dunque esiste.`,
   nodo:`Dall'analisi di un concetto si può ricavare che qualcosa esiste fuori dalla mente.`},
  [`Tommaso d'Aquino`]:{a:`1225-1274`, pos:`Sì, partendo dal mondo`, f:`Cinque vie, e tutte cominciano da ciò che si vede.`,
   d:`Movimento, causa efficiente, contingenza, gradi di perfezione, ordine: cinque catene che non possono risalire all'infinito. Rifiuta esplicitamente la prova di Anselmo, perché dell'essenza di Dio non abbiamo idea.`,
   nodo:`Si ragiona sempre a partire dall'esperienza, mai da una definizione.`},
  [`Pascal`]:{a:`1623-1662`, pos:`No, e non serve`, f:`Dio di Abramo, non dei filosofi e dei dotti.`,
   d:`Le prove non convertono nessuno: chi crede non ne ha bisogno, chi non crede non ne è persuaso. Resta la scommessa, che non è un argomento ma un calcolo su come conviene giocare quando non si sa.`,
   nodo:`La questione non è teorica ma pratica: si tratta di come vivere, non di che cosa concludere.`},
  [`Spinoza`]:{a:`1632-1677`, pos:`Sì, ma non è quel Dio`, f:`Deus sive Natura.`,
   d:`La sostanza infinita esiste necessariamente, perché la sua essenza implica l'esistenza. Ma non ha intelletto né volontà come li intendiamo, non ha scopi, non premia e non punisce.`,
   nodo:`Ciò che si dimostra e ciò che si prega possono non essere la stessa cosa.`},
  [`Hume`]:{a:`1711-1776`, pos:`No`, f:`Dall'ordine del mondo non segue un architetto perfetto.`,
   d:`Se si risale dall'effetto alla causa, si può risalire solo a una causa proporzionata: e questo mondo è pieno di sprechi, dolori e tentativi mal riusciti. Se ne inferirebbe un artigiano mediocre, o una squadra.`,
   nodo:`L'inferenza non può concludere più di quanto l'esperienza contenga.`},
  [`Kant`]:{a:`1724-1804`, pos:`No, ma va postulato`, f:`L'esistenza non è un predicato reale.`,
   d:`Cento talleri pensati hanno lo stesso concetto di cento posseduti: aggiungere «esiste» non arricchisce la definizione. Le prove cadono. Ma la ragione pratica esige di postulare Dio perché virtù e felicità possano coincidere.`,
   nodo:`Si conosce solo entro l'esperienza; ciò che la oltrepassa si può pensare, non provare.`},
  [`Feuerbach`]:{a:`1804-1872`, pos:`No, ed è una proiezione`, f:`È l'uomo che ha fatto Dio a propria immagine.`,
   d:`Prendiamo le qualità che ammiriamo in noi, le portiamo all'infinito, le mettiamo fuori e le adoriamo. La domanda giusta non è se esista, ma di che cosa è fatto il bisogno che lo produce.`,
   nodo:`Le idee religiose vanno spiegate a partire dagli uomini che le hanno.`}
 }},
{
 k:`felicita`, q:`Che cos'è una vita riuscita?`,
 r:{
  [`Aristotele`]:{a:`384-322 a.C.`, pos:`Attività secondo virtù`, f:`Una rondine non fa primavera.`,
   d:`Non uno stato d'animo ma un fare bene ciò che è proprio dell'uomo, per una vita intera. Servono anche beni esterni, amici e un po' di fortuna: la felicità non è del tutto in nostro potere.`,
   nodo:`Si giudica alla fine e sull'insieme, non nel momento.`},
  [`Epicuro`]:{a:`341-270 a.C.`, pos:`Assenza di dolore e turbamento`, f:`Pane e acqua bastano, tolto il superfluo.`,
   d:`Il piacere è la cessazione di un bisogno, non un accumulo. Si distinguono i desideri naturali e necessari dagli altri, e ci si libera da quattro paure: gli dèi, la morte, il dolore, il non ottenere il bene.`,
   nodo:`Il bene è il piacere, ma inteso in negativo: come mancanza di ciò che turba.`},
  [`Epitteto`]:{a:`50-135 ca.`, pos:`Padronanza di sé`, f:`Alcune cose dipendono da noi, altre no.`,
   d:`Corpo, reputazione, beni e altri non dipendono da noi; giudizi e desideri sì. Chi confonde i due elenchi sarà infelice; chi li distingue è libero anche in catene, ed è uno schiavo liberto a scriverlo.`,
   nodo:`La felicità sta tutta nella disposizione interiore, mai nelle circostanze.`},
  [`Agostino`]:{a:`354-430`, pos:`Non è raggiungibile quaggiù`, f:`Il nostro cuore è inquieto finché non riposa in te.`,
   d:`Tutti vogliamo essere felici e quasi nessuno sa in che cosa consista. Nessuna cosa finita corrisponde a un desiderio senza misura: da qui l'inquietudine, che è il segno e non l'errore.`,
   nodo:`Il desiderio umano eccede per struttura ogni oggetto disponibile.`},
  [`Bentham`]:{a:`1748-1832`, pos:`Il massimo piacere per il maggior numero`, f:`Piacere e dolore sono i due padroni.`,
   d:`Si possono misurare per intensità, durata, certezza, vicinanza, fecondità, purezza ed estensione. Su quel calcolo si scrivono le leggi, e non sulle opinioni di chi le scrive.`,
   nodo:`Il bene è una quantità, e quindi in linea di principio si può contare.`},
  [`Kant`]:{a:`1724-1804`, pos:`Non è il criterio morale`, f:`Non essere felici: rendersene degni.`,
   d:`Il concetto di felicità è così indeterminato che nessuno sa dire con precisione che cosa vuole. Non può fondare un dovere. Ciò che si può volere universalmente non è il piacere ma la legge.`,
   nodo:`Un principio morale deve valere per chiunque, e la felicità non è la stessa per nessuno.`},
  [`Schopenhauer`]:{a:`1788-1860`, pos:`Non esiste, c'è solo sollievo`, f:`Come un pendolo fra dolore e noia.`,
   d:`La volontà è mancanza; ottenuto ciò che si voleva subentra il vuoto. Il piacere è negativo, mai positivo. Resta il sollievo dell'arte, della compassione, dell'ascesi.`,
   nodo:`Il desiderio è per natura insaziabile: la meta non c'è, c'è solo l'alternanza.`},
  [`Nietzsche`]:{a:`1844-1900`, pos:`Poter dire sì a ciò che si è vissuto`, f:`«Noi abbiamo inventato la felicità», dicono gli ultimi uomini.`,
   d:`Una vita organizzata per evitare ogni dolore produce un uomo piccolo e prudente. Ciò che conta è l'intensità, al punto da desiderare ancora tutto quello che è accaduto.`,
   nodo:`Cercare direttamente il benessere è un sintomo di stanchezza, non un obiettivo.`}
 }},
{
 k:`liberta`, q:`Siamo davvero liberi?`,
 r:{
  [`Socrate`]:{a:`470-399 a.C.`, pos:`Sì, se si conosce il bene`, f:`Nessuno fa il male volontariamente.`,
   d:`Chi sbaglia lo fa per ignoranza: se sapesse davvero che cosa gli conviene lo farebbe. Il vizio è un errore di calcolo, e la libertà coincide con il sapere.`,
   nodo:`Sapere e volere non possono divergere: chi vede il bene lo sceglie.`},
  [`Aristotele`]:{a:`384-322 a.C.`, pos:`Sì, e per questo si è responsabili`, f:`Volontario è ciò di cui il principio sta in noi.`,
   d:`Si può conoscere il bene e fare il male: la passione acceca sul momento. Ma le abitudini che ci hanno resi così le abbiamo costruite noi, un atto per volta.`,
   nodo:`La responsabilità sta nel carattere, e il carattere è un prodotto delle scelte passate.`},
  [`Agostino`]:{a:`354-430`, pos:`Sì, ma la volontà è malata`, f:`Volere e non potere: questa è la ferita.`,
   d:`Comando alla mia volontà e non mi obbedisce. La libertà c'è, ma è divisa contro se stessa, e da sola non basta a guarirsi.`,
   nodo:`Il conflitto non è fra ragione e passione ma dentro il volere stesso.`},
  [`Spinoza`]:{a:`1632-1677`, pos:`No, ed è un'illusione`, f:`Una pietra che pensasse crederebbe di volare per scelta.`,
   d:`Gli uomini si credono liberi perché sono coscienti delle proprie azioni e ignorano le cause che le determinano. Libertà non è assenza di cause: è agire secondo la propria natura, e si conquista capendo.`,
   nodo:`Tutto ha una causa: sentirsi liberi è ignoranza, esserlo è comprensione.`},
  [`Kant`]:{a:`1724-1804`, pos:`Sì, ma non lo si può provare`, f:`Autonomia: darsi da sé la propria legge.`,
   d:`Nel mondo dei fenomeni tutto è determinato. Ma ogni volta che dico «devo» presuppongo di poter fare altrimenti: la libertà non si dimostra, si postula come condizione della morale.`,
   nodo:`Ciò che è indimostrabile teoricamente può essere necessario praticamente.`},
  [`Marx`]:{a:`1818-1883`, pos:`Solo formalmente`, f:`Libero di vendere la propria forza lavoro.`,
   d:`Nessuno obbliga l'operaio a firmare. Ma non possiede i mezzi per vivere altrimenti, e una libertà senza le condizioni per esercitarla è una parola che copre una costrizione.`,
   nodo:`Un diritto vale quanto le condizioni materiali che lo rendono esercitabile.`},
  [`Sartre`]:{a:`1905-1980`, pos:`Sì, e non se ne esce`, f:`Siamo condannati a essere liberi.`,
   d:`Non c'è una natura umana che decida per noi: prima esistiamo, poi ci definiamo con quello che facciamo. Anche non scegliere è scegliere, e la responsabilità non si passa a nessuno.`,
   nodo:`Nessuna essenza precede l'esistenza: quindi nessuna scusa è disponibile.`},
  [`Freud`]:{a:`1856-1939`, pos:`Molto meno di quanto crediamo`, f:`L'io non è padrone in casa propria.`,
   d:`Le ragioni che ci diamo sono spesso ricostruzioni a posteriori di spinte che non conosciamo. Non si nega la scelta: si nega che chi sceglie sappia perché.`,
   nodo:`La coscienza è una parte piccola e non la più decisiva della vita psichica.`}
 }},
{
 k:`morale`, q:`Da dove viene il dovere morale?`,
 r:{
  [`Platone`]:{a:`427-347 a.C.`, pos:`Da un ordine che c'è già`, f:`Il bene sta al di là dell'essere.`,
   d:`Il bene non è ciò che ci piace o ci conviene: è ciò che rende intelligibile tutto il resto, come il sole rende visibili le cose. Si scopre, non si stabilisce.`,
   nodo:`Esiste un ordine oggettivo del valore, indipendente da chi lo riconosce.`},
  [`Aristotele`]:{a:`384-322 a.C.`, pos:`Dall'esercizio, non da una regola`, f:`Le virtù si acquistano facendo.`,
   d:`Si diventa giusti compiendo atti giusti, come si diventa citaristi suonando. Non esiste una formula: esiste il giusto mezzo, che varia con le persone e le situazioni, e l'uomo prudente che lo trova.`,
   nodo:`La morale è una competenza pratica, non un sistema di proposizioni.`},
  [`Hume`]:{a:`1711-1776`, pos:`Dal sentimento`, f:`La ragione è schiava delle passioni.`,
   d:`Da premesse che dicono come le cose sono non segue mai una conclusione su come devono essere. Il biasimo non lo si vede nel fatto: lo si prova, e nasce dalla simpatia con chi ne soffre.`,
   nodo:`Un fatto, per quanto descritto bene, non produce da solo un obbligo.`},
  [`Kant`]:{a:`1724-1804`, pos:`Dalla ragione stessa`, f:`Agisci come se la tua massima dovesse farsi legge.`,
   d:`Se il dovere dipendesse dai desideri sarebbe condizionato, e non sarebbe un dovere. Vale solo ciò che può essere voluto da chiunque senza contraddizione, e le persone vanno trattate sempre anche come fine.`,
   nodo:`Un obbligo autentico deve essere incondizionato, quindi non può dipendere da fini particolari.`},
  [`Bentham`]:{a:`1748-1832`, pos:`Dalle conseguenze`, f:`La questione non è se possano ragionare, ma se possano soffrire.`,
   d:`Il criterio è quanto piacere e quanto dolore un'azione produce, contando ciascuno per uno. Le intenzioni non pesano: pesa che cosa accade davvero, e a quante creature.`,
   nodo:`Il valore di un'azione sta interamente nei suoi effetti.`},
  [`Nietzsche`]:{a:`1844-1900`, pos:`Da una storia che l'ha nascosta`, f:`Buono e cattivo, buono e malvagio: due scale diverse.`,
   d:`I valori non sono caduti dal cielo: hanno una provenienza, e spesso è il rovesciamento operato dai deboli contro i forti. Chiedere «da dove viene» invece che «è vero» cambia tutto il paesaggio.`,
   nodo:`Ogni valore è un prodotto storico e conserva le tracce di chi lo ha imposto.`},
  [`Hannah Arendt`]:{a:`1906-1975`, pos:`Dal giudicare, che si può smettere`, f:`La banalità del male.`,
   d:`Chi eseguiva gli ordini non era un mostro: aveva smesso di pensare a che cosa stesse facendo, sostituendo il giudizio con il rispetto della procedura. Il male più grande può non avere radici profonde.`,
   nodo:`La moralità dipende da un esercizio — pensare a ciò che si fa — che può semplicemente cessare.`}
 }},
{
 k:`conoscenza`, q:`Da dove viene quello che sappiamo?`,
 r:{
  [`Platone`]:{a:`427-347 a.C.`, pos:`Era già dentro di noi`, f:`Conoscere è ricordare.`,
   d:`Uno schiavo che non ha mai studiato geometria, guidato dalle domande giuste, ricava il teorema da sé: non gli è stato insegnato, l'ha ritrovato. L'anima ha già visto, e l'esperienza risveglia.`,
   nodo:`Non si può cercare ciò di cui non si ha già qualche nozione: dunque qualcosa precede l'esperienza.`},
  [`Aristotele`]:{a:`384-322 a.C.`, pos:`Dai sensi, salendo`, f:`Nulla è nell'intelletto che prima non sia stato nei sensi.`,
   d:`Dai molti casi si forma il ricordo, dai ricordi l'esperienza, dall'esperienza l'universale. La mente è come una tavoletta su cui non c'è ancora scritto nulla.`,
   nodo:`Il generale si ricava dal particolare, mai il contrario.`},
  [`Cartesio`]:{a:`1596-1650`, pos:`Dalla ragione, con un fondamento`, f:`Penso, dunque sono.`,
   d:`I sensi ingannano, e su un fondamento incerto non si costruisce. Si dubita di tutto finché non resta qualcosa di indubitabile, e da lì si procede per evidenza, analisi, sintesi, revisione.`,
   nodo:`La certezza va cercata dentro, perché fuori non c'è nulla che regga al dubbio.`},
  [`Locke`]:{a:`1632-1704`, pos:`Solo dall'esperienza`, f:`La mente è un foglio bianco.`,
   d:`Nessuna idea innata: né nei bambini, né negli idioti, né nei popoli lontani, dove i presunti principi universali non si trovano. Tutto viene da sensazione e riflessione.`,
   nodo:`Se un'idea fosse innata, la si troverebbe in tutti — e non si trova.`},
  [`Hume`]:{a:`1711-1776`, pos:`Dall'abitudine, che non è una prova`, f:`La connessione necessaria non si vede mai.`,
   d:`Vedo la palla colpirne un'altra e la seconda partire, mai il legame fra le due. Lo aggiungo io, perché l'ho visto molte volte: tutta la scienza della natura poggia su un'aspettativa.`,
   nodo:`Vale solo ciò di cui si ha impressione, e della necessità non c'è impressione.`},
  [`Kant`]:{a:`1724-1804`, pos:`Materia dai sensi, forma da noi`, f:`Concetti senza intuizioni sono vuoti.`,
   d:`Né innatismo né empirismo: spazio, tempo e categorie non si ricavano dall'esperienza, la rendono possibile. Perciò la scienza è certa, ma del mondo come ci appare.`,
   nodo:`I due partiti litigavano su una falsa alternativa: le due fonti collaborano.`},
  [`Popper`]:{a:`1902-1994`, pos:`Da congetture che si provano a demolire`, f:`Un cigno nero basta.`,
   d:`Nessun numero di conferme dimostra una legge; una smentita la abbatte. La conoscenza cresce per tentativi audaci ed errori eliminati, e una teoria vale per i rischi che accetta di correre.`,
   nodo:`Non serve fondare il sapere: basta saperlo correggere.`},
  [`Thomas Kuhn`]:{a:`1922-1996`, pos:`Da una comunità e dal suo paradigma`, f:`La scienza normale risolve rompicapi.`,
   d:`Per lunghi periodi i fondamenti non si discutono. Le anomalie si accumulano, arriva la crisi, e il quadro cambia in blocco: con esso cambiano i problemi che contano e il significato dei termini.`,
   nodo:`Il soggetto che conosce non è un individuo ma un gruppo, con la sua storia.`}
 }},
{
 k:`natura`, q:`L'uomo è naturalmente buono?`,
 r:{
  [`Aristotele`]:{a:`384-322 a.C.`, pos:`Né buono né cattivo: da educare`, f:`Per natura politico, per abitudine virtuoso.`,
   d:`La natura ci dà la possibilità della virtù, non la virtù. Nessuna disposizione naturale si cambia con l'abitudine, ma nessuna virtù nasce senza abitudine: le due cose insieme.`,
   nodo:`La natura fornisce potenzialità, la vita in comune decide che cosa ne viene.`},
  [`Agostino`]:{a:`354-430`, pos:`No, è ferito in partenza`, f:`Ho rubato quelle pere non per fame, ma perché era proibito.`,
   d:`Il male che facciamo non si spiega sempre col vantaggio: c'è un compiacimento nel trasgredire in quanto tale. Da qui l'idea che il guasto sia più profondo dell'errore di calcolo.`,
   nodo:`Il male ha una radice nella volontà, non solo nell'ignoranza o nel bisogno.`},
  [`Hobbes`]:{a:`1588-1679`, pos:`No, ma non è colpa sua`, f:`Homo homini lupus.`,
   d:`Non è cattiveria: è che in condizione di scarsità e di uguale vulnerabilità, attaccare per primi è razionale. La guerra di tutti contro tutti è un risultato della situazione, non del carattere.`,
   nodo:`Il comportamento si spiega con gli incentivi della situazione, non con una natura morale.`},
  [`Rousseau`]:{a:`1712-1778`, pos:`Sì, ed è la società a guastarlo`, f:`Tutto è bene uscendo dalle mani dell'Autore delle cose.`,
   d:`L'uomo naturale è autosufficiente e prova pietà spontanea alla vista della sofferenza. Sono la proprietà, il confronto e l'amor proprio a produrre invidia e disuguaglianza.`,
   nodo:`Ciò che chiamiamo natura umana è quasi sempre un prodotto storico che scambiamo per originario.`},
  [`Kant`]:{a:`1724-1804`, pos:`Storto, e proprio per questo capace`, f:`Da un legno storto non si è mai fatto nulla di dritto.`,
   d:`C'è nell'uomo una tendenza al male che non si estirpa. Ma c'è anche la ragione, e l'insocievole socievolezza — il bisogno degli altri unito al fastidio per gli altri — è ciò che spinge a costruire istituzioni.`,
   nodo:`Le disposizioni cattive possono produrre, attraverso il conflitto, risultati buoni.`},
  [`Marx`]:{a:`1818-1883`, pos:`La domanda è mal posta`, f:`L'essenza umana è l'insieme dei rapporti sociali.`,
   d:`Non esiste una natura umana fissa da giudicare buona o cattiva: gli uomini sono ciò che le condizioni in cui producono la loro vita li rende, e quelle condizioni cambiano.`,
   nodo:`Nessuna caratteristica umana va presa come dato: va spiegata storicamente.`},
  [`Freud`]:{a:`1856-1939`, pos:`No, e la civiltà lo sa`, f:`Il prossimo non è solo un possibile aiuto: è una tentazione.`,
   d:`Sotto le buone maniere c'è una quota di aggressività che la civiltà deve continuamente arginare, rivolgendola all'interno sotto forma di senso di colpa. Il prezzo dell'ordine è il disagio.`,
   nodo:`Le pulsioni non spariscono: si spostano, e il costo si paga altrove.`}
 }},
{
 k:`storia`, q:`La storia va da qualche parte?`,
 r:{
  [`Polibio`]:{a:`200-118 a.C. ca.`, pos:`No, gira in cerchio`, f:`Le costituzioni si succedono e ritornano.`,
   d:`Monarchia, tirannide, aristocrazia, oligarchia, democrazia, governo della folla, e si ricomincia. Roma dura perché mescola le tre forme buone, e ciascuna frena le altre.`,
   nodo:`Le forme politiche hanno una dinamica interna che si ripete: nessuna direzione, solo un ciclo.`},
  [`Agostino`]:{a:`354-430`, pos:`Sì, verso una fine`, f:`Un inizio, un centro, un compimento.`,
   d:`Il tempo non ritorna: va dalla creazione al giudizio, con al centro un evento irripetibile. Gli imperi che sorgono e cadono non sono il senso della vicenda ma il suo sfondo.`,
   nodo:`Il senso della storia non sta dentro la storia: le viene da fuori.`},
  [`Vico`]:{a:`1668-1744`, pos:`Sì, ma per corsi e ricorsi`, f:`Il vero e il fatto si convertono.`,
   d:`Le nazioni percorrono le stesse tre età — degli dèi, degli eroi, degli uomini — poi decadono e ricominciano, non identiche. E la storia si può conoscere perché l'hanno fatta gli uomini.`,
   nodo:`Si conosce davvero solo ciò che si è prodotto: quindi la storia più della natura.`},
  [`Hegel`]:{a:`1770-1831`, pos:`Sì, verso la libertà`, f:`La storia universale è progresso nella coscienza della libertà.`,
   d:`Uno era libero nei dispotismi, alcuni nel mondo antico, tutti nel mondo moderno. Gli individui perseguono i propri fini e realizzano senza saperlo un disegno: è l'astuzia della ragione.`,
   nodo:`Nel corso apparentemente caotico degli eventi opera una razionalità che si può ricostruire.`},
  [`Marx`]:{a:`1818-1883`, pos:`Sì, e il motore è materiale`, f:`Non la coscienza determina l'essere.`,
   d:`Il motore non sono le idee ma il modo in cui gli uomini producono la loro vita e i conflitti che ne nascono. Gli uomini fanno la propria storia, ma non in circostanze scelte da loro.`,
   nodo:`Le condizioni economiche spiegano le idee, non viceversa.`},
  [`Nietzsche`]:{a:`1844-1900`, pos:`No, e credere di sì fa male`, f:`Sull'utilità e il danno della storia per la vita.`,
   d:`Un eccesso di sapere storico paralizza: si diventa spettatori eruditi invece che capaci di agire. La domanda non è se la storia abbia un senso, ma che cosa fa a chi la studia.`,
   nodo:`Una conoscenza va giudicata anche per i suoi effetti su chi la possiede.`},
  [`Walter Benjamin`]:{a:`1892-1940`, pos:`Ci va, ma è una catastrofe`, f:`L'angelo vede un'unica rovina che accumula macerie.`,
   d:`La storia la scrivono i vincitori, e l'empatia dello storico va di solito a loro. Ciò che dall'alto sembra progresso, visto dai vinti è la tempesta che spinge l'angelo lontano dal paradiso.`,
   nodo:`Il punto di vista da cui si racconta decide che cosa si vede: non esiste una posizione neutra.`},
  [`Fernand Braudel`]:{a:`1902-1985`, pos:`Dipende a che velocità si guarda`, f:`Tre tempi sovrapposti.`,
   d:`Sotto la schiuma degli avvenimenti stanno i cicli economici di decenni, e sotto ancora le strutture quasi immobili: clima, suolo, rotte. Una battaglia è un increspamento in superficie.`,
   nodo:`La domanda sul senso dipende dalla scala temporale che si sceglie, e la scelta non è innocente.`}
 }},
{
 k:`arte`, q:`A che cosa serve l'arte?`,
 r:{
  [`Platone`]:{a:`427-347 a.C.`, pos:`A poco, e può fare danno`, f:`Copia di una copia, lontana tre volte dal vero.`,
   d:`Il pittore ritrae il letto del falegname, che a sua volta imita l'idea di letto. E la poesia nutre la parte passionale dell'anima: per questo, nella città giusta, i poeti vanno incoronati e accompagnati fuori.`,
   nodo:`Il valore si misura sulla distanza dal vero, e l'arte ne aggiunge.`},
  [`Aristotele`]:{a:`384-322 a.C.`, pos:`A conoscere e a scaricare`, f:`Impariamo guardando immagini di cose che dal vero ci ripugnerebbero.`,
   d:`L'imitazione è naturale all'uomo e produce piacere perché è apprendimento. La tragedia, suscitando pietà e terrore, opera la purificazione di quelle emozioni.`,
   nodo:`Un'esperienza finta può avere effetti veri su chi la attraversa.`},
  [`Kant`]:{a:`1724-1804`, pos:`A niente, ed è questo il punto`, f:`Un piacere disinteressato.`,
   d:`Il bello piace senza concetto e senza scopo: non lo si giudica utile né vero. Eppure il giudizio pretende l'accordo di chiunque, e questa pretesa senza prova è ciò che rende interessante la faccenda.`,
   nodo:`Esiste un tipo di valore che non si riduce né alla conoscenza né all'utilità.`},
  [`Hegel`]:{a:`1770-1831`, pos:`A far apparire il vero nella forma sensibile`, f:`L'arte è cosa del passato.`,
   d:`Nelle epoche antiche l'arte era il modo più alto in cui un popolo diceva ciò che riteneva vero. Oggi quel compito è passato alla filosofia: l'arte resta bellissima, ma non è più il luogo in cui si decide.`,
   nodo:`Le forme dello spirito hanno un'epoca, e ciò che è stato centrale può cessare di esserlo.`},
  [`Schopenhauer`]:{a:`1788-1860`, pos:`A sospendere il desiderio`, f:`Nella contemplazione la ruota di Issione si ferma.`,
   d:`Guardando un'opera si smette per un momento di volere qualcosa, e con il volere cessa il dolore. La musica soprattutto, perché non copia gli oggetti: dice direttamente la volontà.`,
   nodo:`Il male della vita è il desiderio, quindi ogni tregua dal desiderio è un bene.`},
  [`Nietzsche`]:{a:`1844-1900`, pos:`A rendere sopportabile la verità`, f:`Abbiamo l'arte per non morire della verità.`,
   d:`I greci non erano sereni: sapevano quanto la vita sia terribile, e hanno inventato la forma per poterla guardare. Apollineo e dionisiaco non sono stili ma due modi di reggere l'esistenza.`,
   nodo:`Non è la verità a essere il valore supremo: è ciò che permette di continuare a vivere.`},
  [`Walter Benjamin`]:{a:`1892-1940`, pos:`Dipende da come si riproduce`, f:`L'aura svanisce nell'epoca della riproducibilità tecnica.`,
   d:`La fotografia e il cinema tolgono all'opera l'unicità del qui e ora. Si perde qualcosa — il valore rituale — ma si guadagna la possibilità di un'arte politica, che raggiunga le masse invece di essere contemplata.`,
   nodo:`La tecnica con cui un'opera esiste cambia che cosa quell'opera può fare.`}
 }}
];
