/* ══════════════════════════════════════════════════════════
   GLI EVENTI DELLA LINEA DEL TEMPO
   Ricavati dalle slide: un fatto per ogni snodo che in classe
   viene davvero raccontato. Ogni voce ha:
     a  = anno (negativo per gli anni prima di Cristo)
     m  = materia: 's' storia, 'f' filosofia
     t  = titolo, cioè come lo si chiama a lezione
     d  = una riga che dice perché conta
   L'ordine nel file non ha importanza: la pagina riordina.
   ══════════════════════════════════════════════════════════ */
const EVENTI = [

/* ── MONDO ANTICO ───────────────────────────────────────── */
{a:-3500,m:'s',t:'Nasce la scrittura in Mesopotamia',d:'Con i segni sull\'argilla comincia ciò che chiamiamo storia: prima di allora ci sono i fatti, non i documenti.'},
{a:-1750,m:'s',t:'Il codice di Hammurabi',d:'Le regole vengono incise sulla pietra: chi comanda non può più cambiarle a piacere ogni mattina.'},
{a:-753,m:'s',t:'Fondazione di Roma',d:'La data che i Romani stessi si daranno per cominciare a contare gli anni.'},
{a:-624,m:'f',t:'Talete di Mileto',d:'Per la prima volta qualcuno spiega il mondo senza chiamare in causa gli dèi: tutto viene dall\'acqua.'},
{a:-570,m:'f',t:'Pitagora e i numeri',d:'Se la realtà si lascia misurare, allora ha una struttura: il numero come chiave delle cose.'},
{a:-540,m:'f',t:'Eraclito: tutto scorre',d:'Nulla resta uguale a sé stesso. La guerra dei contrari è ciò che tiene insieme il mondo.'},
{a:-510,m:'s',t:'Roma diventa repubblica',d:'Cacciato il re, il potere si divide fra magistrature che durano un anno.'},
{a:-500,m:'f',t:'Parmenide: l\'essere è',d:'Il rovescio di Eraclito: se una cosa è, non può non essere. Nasce la logica.'},
{a:-490,m:'s',t:'Le guerre persiane',d:'Poche città greche fermano il più grande impero del mondo: da qui l\'idea che l\'Occidente sia altro dall\'Oriente.'},
{a:-450,m:'f',t:'I sofisti',d:'Insegnano a parlare bene a pagamento. Se ogni tesi ha la sua contraria, chi decide qual è vera?'},
{a:-399,m:'f',t:'La morte di Socrate',d:'Condannato dalla città che diceva di voler rendere migliore. Muore per non rinnegare il proprio metodo.'},
{a:-387,m:'f',t:'Platone apre l\'Accademia',d:'Le cose che vediamo sono copie: le idee stanno altrove e sono quelle vere.'},
{a:-335,m:'f',t:'Aristotele e il Liceo',d:'Riporta le idee dentro le cose e mette ordine in tutto lo scibile: logica, fisica, etica, politica.'},
{a:-323,m:'s',t:'Muore Alessandro Magno',d:'Il suo impero si spezza, ma la cultura greca resta padrona di tutto il Mediterraneo orientale.'},
{a:-306,m:'f',t:'Epicuro e il Giardino',d:'La filosofia come cura: togliere la paura degli dèi e della morte per vivere sereni.'},
{a:-300,m:'f',t:'Nasce lo stoicismo',d:'Non possiamo scegliere ciò che accade, solo come stargli davanti.'},
{a:-146,m:'s',t:'Roma distrugge Cartagine',d:'Il Mediterraneo diventa un lago romano.'},
{a:-44,m:'s',t:'L\'assassinio di Cesare',d:'La repubblica prova a difendersi da un uomo solo, e proprio così finisce.'},
{a:-27,m:'s',t:'Augusto e il principato',d:'Un potere personale con le forme della repubblica: durerà tre secoli.'},

/* ── TARDOANTICO E MEDIOEVO ─────────────────────────────── */
{a:313,m:'s',t:'Editto di Milano',d:'Il cristianesimo smette di essere perseguitato: in pochi decenni diventerà la religione dell\'impero.'},
{a:250,m:'f',t:'Plotino e il neoplatonismo',d:'Tutto discende da un Uno indicibile: la filosofia greca prende la forma che passerà al cristianesimo.'},
{a:397,m:'f',t:'Le Confessioni di Agostino',d:'La prima volta che un filosofo racconta sé stesso: il tempo, la memoria, la volontà divisa.'},
{a:476,m:'s',t:'Cade l\'impero d\'Occidente',d:'Non un crollo in un giorno: la fine di un\'organizzazione che non reggeva più.'},
{a:622,m:'s',t:'L\'Egira: nasce l\'islam',d:'In un secolo una nuova religione unifica dalla Spagna alla Persia.'},
{a:800,m:'s',t:'Carlo Magno imperatore',d:'L\'idea di impero torna in Occidente, e nasce il nodo fra potere del re e potere del papa.'},
{a:1000,m:'s',t:'La ripresa dell\'anno Mille',d:'Più cibo, più gente, più città: l\'Europa ricomincia a crescere.'},
{a:1077,m:'s',t:'Canossa',d:'L\'imperatore aspetta tre giorni nella neve: chi comanda davvero, il papa o il re?'},
{a:1095,m:'s',t:'La prima crociata',d:'In centomila partono per Gerusalemme. Fede, terra, mercato: le ragioni sono tutte insieme.'},
{a:1088,m:'s',t:'Nasce l\'università di Bologna',d:'Il sapere esce dai monasteri e si organizza in corporazioni di studenti e maestri.'},
{a:1215,m:'s',t:'La Magna Carta',d:'Anche il re deve rispondere a delle regole: il primo mattone del costituzionalismo.'},
{a:1265,m:'f',t:'Tommaso e la Summa',d:'Fede e ragione non si contraddicono: si può dimostrare con Aristotele ciò in cui si crede.'},
{a:1300,m:'f',t:'Ockham e il rasoio',d:'Non moltiplicare gli enti senza necessità: comincia lo smontaggio della metafisica medievale.'},
{a:1348,m:'s',t:'La peste nera',d:'Muore un europeo su tre. Chi resta vale di più: cambiano salari, campagne, mentalità.'},
{a:1453,m:'s',t:'Cade Costantinopoli',d:'Finisce l\'impero romano d\'Oriente e i dotti greci portano in Italia i loro libri.'},

/* ── ETÀ MODERNA ────────────────────────────────────────── */
{a:1440,m:'s',t:'La stampa di Gutenberg',d:'Le idee cominciano a viaggiare più veloci di chi le vieta.'},
{a:1492,m:'s',t:'Colombo arriva in America',d:'Due mondi che si ignoravano si toccano: comincia il primo scambio davvero globale.'},
{a:1513,m:'f',t:'Machiavelli scrive il Principe',d:'La politica si studia per quello che è, non per quello che dovrebbe essere.'},
{a:1517,m:'s',t:'Lutero e le 95 tesi',d:'La cristianità occidentale si spezza e nessuno riuscirà più a ricucirla.'},
{a:1543,m:'s',t:'Copernico: la Terra si muove',d:'Il pianeta perde il centro dell\'universo. Non è un dettaglio tecnico: è una ferita.'},
{a:1545,m:'s',t:'Il concilio di Trento',d:'La Chiesa di Roma si riorganizza: dogmi, seminari, indice dei libri proibiti.'},
{a:1600,m:'f',t:'Giordano Bruno al rogo',d:'Universo infinito e mondi innumerevoli: pagato con la vita in Campo de\' Fiori.'},
{a:1610,m:'f',t:'Galileo e il cannocchiale',d:'Guardare per decidere. La prova sperimentale prende il posto dell\'autorità del testo.'},
{a:1618,m:'s',t:'La guerra dei Trent\'anni',d:'Trent\'anni di guerra di religione lasciano la Germania devastata e l\'Europa laica per stanchezza.'},
{a:1637,m:'f',t:'Il Discorso sul metodo',d:'Cartesio dubita di tutto per trovare l\'unica cosa indubitabile: che sta dubitando.'},
{a:1648,m:'s',t:'La pace di Vestfalia',d:'Nasce l\'idea di Stato sovrano: dentro i suoi confini nessuno comanda al posto suo.'},
{a:1651,m:'f',t:'Il Leviatano di Hobbes',d:'Senza uno Stato che spaventi tutti, la vita è solitaria, povera, brutale e breve.'},
{a:1687,m:'s',t:'I Principia di Newton',d:'Una sola legge per la mela e per i pianeti: il cielo e la terra obbediscono alle stesse regole.'},
{a:1690,m:'f',t:'Locke e i due trattati',d:'Il potere nasce da un patto e può essere revocato: la base teorica delle rivoluzioni che verranno.'},
{a:1748,m:'f',t:'Montesquieu e i tre poteri',d:'Solo il potere può fermare il potere: dividerlo in tre è la garanzia della libertà.'},
{a:1751,m:'f',t:'L\'Encyclopédie',d:'Mettere tutto il sapere in ordine alfabetico e alla portata di chiunque sappia leggere.'},
{a:1762,m:'f',t:'Rousseau e il contratto sociale',d:'L\'uomo è nato libero e dovunque è in catene. La sovranità appartiene al popolo.'},
{a:1748,m:'f',t:'Hume e la critica della causa',d:'Che il sole sorgerà domani non è una certezza: è un\'abitudine.'},

/* ── OTTOCENTO ──────────────────────────────────────────── */
{a:1776,m:'s',t:'Indipendenza americana',d:'Per la prima volta un popolo si dà da sé una costituzione scritta.'},
{a:1781,m:'f',t:'La Critica della ragion pura',d:'Kant: non è la mente che si adegua alle cose, sono le cose che passano dalle forme della mente.'},
{a:1789,m:'s',t:'La Rivoluzione francese',d:'Cadono i privilegi di nascita. Libertà, uguaglianza e terrore nello stesso decennio.'},
{a:1785,m:'f',t:'La legge morale in noi',d:'Kant: agisci solo secondo quella regola che vorresti valesse per tutti.'},
{a:1799,m:'s',t:'Napoleone al potere',d:'Esporta i codici della rivoluzione a colpi di cannone, e si fa incoronare imperatore.'},
{a:1807,m:'f',t:'La Fenomenologia di Hegel',d:'La coscienza cresce attraverso i suoi conflitti: servo e signore hanno bisogno l\'uno dell\'altro.'},
{a:1815,m:'s',t:'Il congresso di Vienna',d:'I re rimettono a posto la carta d\'Europa fingendo che il 1789 non sia mai accaduto.'},
{a:1819,m:'f',t:'Schopenhauer: il mondo come volontà',d:'Dietro le cose non c\'è ragione ma una spinta cieca a vivere. Perciò si soffre.'},
{a:1830,m:'s',t:'La prima rivoluzione industriale',d:'Il vapore, la fabbrica, la città: in due generazioni cambia il modo di lavorare e di vivere.'},
{a:1843,m:'f',t:'Kierkegaard: aut-aut',d:'Non esiste una sintesi che concili tutto: bisogna scegliere, e la scelta angoscia.'},
{a:1848,m:'s',t:'La primavera dei popoli',d:'Mezza Europa insorge nello stesso anno. Quasi tutte le rivolte falliscono, nessuna passa senza lasciare traccia.'},
{a:1848,m:'f',t:'Il Manifesto di Marx ed Engels',d:'La storia di ogni società è storia di lotte di classi.'},
{a:1859,m:'s',t:'Darwin e l\'origine delle specie',d:'Le specie non sono create una volta per tutte: cambiano, e l\'uomo con loro.'},
{a:1861,m:'s',t:'L\'Unità d\'Italia',d:'Nasce uno Stato che deve ancora inventarsi gli italiani.'},
{a:1861,m:'s',t:'La guerra civile americana',d:'Si combatte sulla schiavitù e sul modello economico di un continente intero.'},
{a:1867,m:'f',t:'Il Capitale',d:'Marx smonta il meccanismo del profitto: il plusvalore è lavoro non pagato.'},
{a:1871,m:'s',t:'Nasce l\'impero tedesco',d:'Bismarck unifica la Germania con tre guerre: l\'equilibrio europeo non sarà più lo stesso.'},
{a:1882,m:'f',t:'Nietzsche: Dio è morto',d:'Non un annuncio ateo ma una diagnosi: è finita la fiducia in un fondamento che garantisca il senso.'},
{a:1885,m:'s',t:'La spartizione dell\'Africa',d:'Le potenze europee si dividono un continente attorno a un tavolo, a Berlino.'},
{a:1899,m:'f',t:'Freud e l\'interpretazione dei sogni',d:'L\'io non è padrone in casa propria: sotto la coscienza lavorano forze che non conosciamo.'},

/* ── NOVECENTO ──────────────────────────────────────────── */
{a:1900,m:'s',t:'La Belle Époque',d:'L\'Europa si crede al culmine del progresso, mentre prepara la sua guerra civile.'},
{a:1903,m:'s',t:'L\'Italia giolittiana',d:'Industria al Nord, emigrazione al Sud, e per la prima volta lo Stato tratta con i sindacati.'},
{a:1905,m:'s',t:'Einstein e la relatività',d:'Spazio e tempo smettono di essere il fondale immobile del mondo.'},
{a:1907,m:'f',t:'Bergson e la durata',d:'Il tempo vissuto non è quello dell\'orologio: dentro di noi i momenti si compenetrano.'},
{a:1913,m:'f',t:'Husserl e la fenomenologia',d:'Tornare alle cose stesse: descrivere come il mondo si dà alla coscienza, prima di spiegarlo.'},
{a:1914,m:'s',t:'Scoppia la Grande guerra',d:'Doveva finire per Natale. Durò quattro anni e uccise dieci milioni di soldati.'},
{a:1917,m:'s',t:'La rivoluzione russa',d:'Per la prima volta un partito marxista prende il potere in uno Stato.'},
{a:1919,m:'s',t:'Il trattato di Versailles',d:'Una pace che umilia i vinti e prepara il conflitto successivo.'},
{a:1921,m:'f',t:'Il Tractatus di Wittgenstein',d:'Su ciò di cui non si può parlare, si deve tacere.'},
{a:1922,m:'s',t:'La marcia su Roma',d:'In tre anni il fascismo passa dal governo alla dittatura.'},
{a:1927,m:'f',t:'Essere e tempo',d:'Heidegger: siamo gettati nel mondo e ci muoviamo verso la morte. L\'angoscia ci restituisce a noi stessi.'},
{a:1929,m:'s',t:'La crisi del \'29',d:'Da Wall Street la rovina arriva ovunque: milioni senza lavoro e la democrazia sotto accusa.'},
{a:1933,m:'s',t:'Hitler al potere',d:'Arriva con le elezioni e smonta la democrazia in pochi mesi, dall\'interno.'},
{a:1936,m:'s',t:'La guerra civile spagnola',d:'La prova generale della seconda guerra mondiale, combattuta da mezzo mondo.'},
{a:1939,m:'s',t:'La seconda guerra mondiale',d:'Sei anni, sessanta milioni di morti, e per la prima volta più civili che soldati.'},
{a:1942,m:'s',t:'La Shoah',d:'Lo sterminio pianificato di sei milioni di ebrei, organizzato come una procedura amministrativa.'},
{a:1944,m:'f',t:'Dialettica dell\'illuminismo',d:'Horkheimer e Adorno: la ragione che doveva liberarci si è rovesciata in dominio.'},
{a:1945,m:'s',t:'Hiroshima',d:'Con l\'atomica l\'umanità acquista per la prima volta il potere di finire.'},
{a:1946,m:'s',t:'L\'Italia sceglie la repubblica',d:'Il 2 giugno votano per la prima volta anche le donne.'},
{a:1948,m:'s',t:'La Costituzione italiana',d:'Uguaglianza, lavoro, pluralismo, ripudio della guerra: le regole nate dall\'antifascismo.'},
{a:1948,m:'s',t:'Dichiarazione dei diritti umani',d:'Dopo la guerra, il tentativo di scrivere ciò che nessuno Stato può fare a nessun essere umano.'},
{a:1947,m:'s',t:'Comincia la guerra fredda',d:'Due blocchi, due sistemi, un equilibrio tenuto in piedi dalla paura reciproca.'},
{a:1943,m:'f',t:'L\'essere e il nulla',d:'Sartre: l\'esistenza precede l\'essenza, siamo condannati a essere liberi.'},
{a:1951,m:'f',t:'Le origini del totalitarismo',d:'Arendt: ideologia più terrore. Il bersaglio non è l\'oppositore ma la capacità di cominciare qualcosa.'},
{a:1953,m:'f',t:'Le Ricerche filosofiche',d:'Il secondo Wittgenstein demolisce il primo: il significato di una parola è il suo uso.'},
{a:1957,m:'s',t:'I trattati di Roma',d:'Sei paesi che si erano appena massacrati decidono di mettere in comune il carbone e l\'acciaio.'},
{a:1958,m:'s',t:'Il miracolo economico italiano',d:'In dieci anni un paese agricolo diventa una potenza industriale.'},
{a:1958,m:'f',t:'Vita activa',d:'Arendt: lavoro, opera e azione. Solo agendo fra gli altri si mostra chi siamo.'},
{a:1961,m:'s',t:'Il muro di Berlino',d:'Una città tagliata in due per impedire alla gente di andarsene.'},
{a:1963,m:'f',t:'La banalità del male',d:'Arendt al processo Eichmann: per fare un male enorme può bastare smettere di pensare.'},
{a:1966,m:'f',t:'Le parole e le cose',d:'Foucault: l\'uomo come soggetto fondatore è un\'invenzione recente, e può finire.'},
{a:1968,m:'s',t:'Il Sessantotto',d:'Studenti e operai contestano insieme l\'autorità, la guerra e il modo di vivere dei padri.'},
{a:1969,m:'s',t:'Piazza Fontana',d:'Una bomba a Milano apre gli anni della strategia della tensione.'},
{a:1975,m:'f',t:'Sorvegliare e punire',d:'Foucault: il potere moderno non picchia, dispone gli sguardi. Chi si sente visto si controlla da sé.'},
{a:1978,m:'s',t:'Il caso Moro',d:'Cinquantacinque giorni di prigionia, e lo Stato che decide di non trattare.'},
{a:1989,m:'s',t:'Cade il muro di Berlino',d:'Un annuncio confuso in televisione manda in strada una città intera.'},
{a:1991,m:'s',t:'Finisce l\'Unione Sovietica',d:'Un impero si dissolve senza una guerra: la bandiera scende dal Cremlino il giorno di Natale.'},
{a:1992,m:'s',t:'Tangentopoli',d:'In due anni si sfalda l\'intero sistema dei partiti nato nel 1948.'},

/* ── OGGI ───────────────────────────────────────────────── */
{a:2001,m:'s',t:'L\'11 settembre',d:'La minaccia non è più uno Stato ma una rete senza territorio. Ne seguono due guerre lunghe vent\'anni.'},
{a:2002,m:'s',t:'L\'euro nelle tasche',d:'Dodici paesi rinunciano alla propria moneta senza avere una politica di bilancio comune.'},
{a:2008,m:'s',t:'La crisi finanziaria',d:'Prestiti concessi a chi non poteva restituirli travolgono le banche di mezzo mondo.'},
{a:2015,m:'s',t:'Gli accordi di Parigi',d:'Centonovantasei paesi si impegnano sul clima. Gli impegni presi non bastano.'},
{a:2016,m:'s',t:'Brexit e l\'ondata populista',d:'Chi si sente lasciato indietro dalla globalizzazione trova finalmente una voce politica.'},
{a:2020,m:'s',t:'La pandemia',d:'Il mondo si ferma insieme per la prima volta, e in un anno arriva un vaccino.'},
{a:2022,m:'s',t:'La guerra in Ucraina',d:'La più grande guerra in Europa dal 1945: l\'ordine nato nel 1991 non regge più.'}

];

/* ══════════════════════════════════════════════════════════
   SECONDO STRATO
   La prima passata teneva solo i grandi snodi. Questa scende
   nel dettaglio delle slide: gli autori uno per uno, i passaggi
   interni alle rivoluzioni, i pezzi di storia d'Italia che in
   classe si raccontano per esteso.
   ══════════════════════════════════════════════════════════ */
EVENTI.push(

/* ── Vicino Oriente e Grecia arcaica ───────────────────── */
{a:-3100,m:'s',t:'L\'Egitto si unifica',d:'Alto e Basso Egitto sotto un solo faraone: comincia una civiltà che durerà tremila anni.'},
{a:-2560,m:'s',t:'La piramide di Cheope',d:'Centomila uomini per vent\'anni: la prova che uno Stato sa organizzare il lavoro su scala enorme.'},
{a:-1274,m:'s',t:'La battaglia di Qadesh',d:'Egizi contro Ittiti, e il primo trattato di pace di cui abbiamo il testo.'},
{a:-1200,m:'s',t:'Il crollo dell\'età del bronzo',d:'In cinquant\'anni spariscono imperi, città e scrittura in tutto il Mediterraneo orientale.'},
{a:-1000,m:'s',t:'I Fenici e l\'alfabeto',d:'Ventidue segni al posto di migliaia: scrivere smette di essere mestiere di pochi.'},
{a:-776,m:'s',t:'Le prime Olimpiadi',d:'I Greci si riconoscono come un solo popolo pur restando città rivali.'},
{a:-750,m:'s',t:'La colonizzazione greca',d:'Da Marsiglia al Mar Nero: la Grecia si moltiplica lungo tutte le coste.'},
{a:-621,m:'s',t:'Le leggi di Dracone',d:'Scritte col sangue, dicevano. Ma scritte: nessuno può più inventarsele al momento.'},
{a:-594,m:'s',t:'Le riforme di Solone',d:'Cancella i debiti e vieta la schiavitù per debiti: la povertà non toglie più la libertà.'},
{a:-546,m:'f',t:'Anassimandro e l\'ápeiron',d:'Il principio non può essere una cosa fra le cose: è l\'illimitato, senza forma.'},
{a:-546,m:'f',t:'Anassimene e l\'aria',d:'Condensandosi e rarefacendosi, una sola sostanza spiega tutte le altre.'},
{a:-508,m:'s',t:'Clistene e la democrazia ateniese',d:'Le tribù vengono rimescolate per spezzare il potere delle famiglie: nasce il cittadino.'},
{a:-500,m:'f',t:'Zenone e i paradossi',d:'Achille non raggiunge la tartaruga: se il ragionamento è valido, il movimento è un\'illusione.'},
{a:-495,m:'f',t:'Empedocle e i quattro elementi',d:'Terra, acqua, aria, fuoco, mossi da amore e odio: nulla nasce, tutto si ricompone.'},
{a:-480,m:'s',t:'Termopili e Salamina',d:'Trecento a difendere un passo, e una flotta che vince in uno stretto: la Grecia resiste.'},
{a:-462,m:'s',t:'L\'età di Pericle',d:'Paga chi partecipa alla vita pubblica: anche il povero può fare politica.'},
{a:-460,m:'f',t:'Democrito e gli atomi',d:'Tutto è fatto di corpuscoli indivisibili e vuoto. Duemila anni dopo avrà ragione.'},
{a:-450,m:'f',t:'Protagora: l\'uomo misura',d:'Non esiste una verità sopra di noi: esiste come le cose appaiono a ciascuno.'},
{a:-450,m:'f',t:'Gorgia e la potenza della parola',d:'Nulla esiste; se esistesse non si conoscerebbe; se si conoscesse non si direbbe.'},
{a:-431,m:'s',t:'La guerra del Peloponneso',d:'Atene contro Sparta per ventisette anni: la Grecia si consuma da sola.'},
{a:-430,m:'s',t:'La peste di Atene',d:'Un terzo della città muore, Pericle compreso. Tucidide la racconta da malato.'},
{a:-404,m:'s',t:'Atene si arrende',d:'Cadono le mura, cade l\'impero marittimo, cade per un anno la democrazia.'},
{a:-380,m:'f',t:'Il mito della caverna',d:'Siamo incatenati a guardare ombre e le chiamiamo realtà. Uscire fa male agli occhi.'},
{a:-370,m:'f',t:'La Repubblica di Platone',d:'Uno Stato giusto è come un\'anima giusta: ognuno fa ciò per cui è fatto.'},
{a:-350,m:'f',t:'L\'Etica Nicomachea',d:'La virtù è un punto di mezzo che si impara facendo, non leggendo.'},
{a:-350,m:'f',t:'La Politica di Aristotele',d:'L\'uomo è animale politico: fuori dalla città o è bestia o è dio.'},
{a:-338,m:'s',t:'Cheronea: la fine delle póleis',d:'Filippo II di Macedonia batte Atene e Tebe. La città-stato ha smesso di contare.'},
{a:-334,m:'s',t:'Alessandro parte per l\'Asia',d:'In undici anni arriva all\'Indo e fonde due mondi che si ignoravano.'},
{a:-300,m:'s',t:'La biblioteca di Alessandria',d:'Si prova a raccogliere tutti i libri del mondo in un solo edificio.'},
{a:-287,m:'s',t:'Archimede',d:'Leve, specchi, il principio dei corpi immersi: la matematica diventa macchina.'},
{a:-264,m:'s',t:'La prima guerra punica',d:'Roma si costruisce una flotta da zero e strappa a Cartagine il mare.'},
{a:-218,m:'s',t:'Annibale valica le Alpi',d:'Con gli elefanti, d\'inverno. Vince tre battaglie e non prende Roma.'},
{a:-133,m:'s',t:'I Gracchi',d:'Provano a ridare terra ai contadini poveri e vengono uccisi: la Repubblica non sa riformarsi.'},
{a:-73,m:'s',t:'La rivolta di Spartaco',d:'Settantamila schiavi tengono in scacco Roma per due anni.'},
{a:-49,m:'s',t:'Cesare passa il Rubicone',d:'Il dado è tratto: un generale porta l\'esercito dentro i confini e comincia la guerra civile.'},

/* ── Impero e tardo antico ─────────────────────────────── */
{a:64,m:'s',t:'L\'incendio di Roma',d:'Nerone accusa i cristiani: la prima persecuzione nasce da un capro espiatorio.'},
{a:79,m:'s',t:'L\'eruzione del Vesuvio',d:'Pompei ed Ercolano sepolte: una città quotidiana congelata per diciassette secoli.'},
{a:117,m:'s',t:'L\'impero al massimo',d:'Con Traiano si va dalla Britannia al Golfo Persico. Da qui in poi si difende soltanto.'},
{a:161,m:'f',t:'Marco Aurelio e i Ricordi',d:'Un imperatore scrive a se stesso per ricordarsi di restare uomo.'},
{a:212,m:'s',t:'La cittadinanza a tutti',d:'Caracalla estende il diritto romano a ogni abitante libero dell\'impero.'},
{a:235,m:'s',t:'La crisi del terzo secolo',d:'Cinquant\'anni di imperatori militari, inflazione e frontiere sfondate.'},
{a:284,m:'s',t:'Diocleziano e la tetrarchia',d:'L\'impero è troppo grande per uno solo: si divide in quattro per sopravvivere.'},
{a:325,m:'s',t:'Il concilio di Nicea',d:'L\'imperatore convoca i vescovi: da qui in poi fede e potere si tengono per mano.'},
{a:380,m:'s',t:'Il cristianesimo religione di Stato',d:'Con Teodosio quello che era perseguitato diventa obbligatorio.'},
{a:410,m:'s',t:'Il sacco di Roma',d:'Alarico entra nella città che non vedeva un nemico da ottocento anni.'},
{a:451,m:'s',t:'Attila fermato ai Campi Catalaunici',d:'Romani e Visigoti insieme contro gli Unni: i nemici di ieri combattono fianco a fianco.'},
{a:493,m:'s',t:'Teodorico re d\'Italia',d:'Un re goto governa con funzionari romani: si prova a far convivere due mondi.'},
{a:529,m:'s',t:'Giustiniano chiude l\'Accademia',d:'Novecento anni dopo Platone, la scuola di Atene viene fatta chiudere.'},
{a:534,m:'s',t:'Il Corpus iuris civilis',d:'Mille anni di leggi romane messi in ordine: l\'Europa ci studierà sopra fino all\'Ottocento.'},
{a:568,m:'s',t:'I Longobardi in Italia',d:'La penisola si spezza in due e non tornerà unita per tredici secoli.'},
{a:732,m:'s',t:'Poitiers',d:'L\'avanzata araba in Europa occidentale si ferma.'},
{a:751,m:'s',t:'La carta arriva in Occidente',d:'Catturati a Talas, artigiani cinesi insegnano agli arabi a farla. Cambierà tutto.'},

/* ── Medioevo ──────────────────────────────────────────── */
{a:962,m:'s',t:'Il Sacro Romano Impero',d:'Ottone I incoronato a Roma: l\'impero rinasce, e con esso il conflitto col papato.'},
{a:1054,m:'s',t:'Lo scisma d\'Oriente',d:'Roma e Costantinopoli si scomunicano a vicenda. Non si ricuciranno più.'},
{a:1066,m:'s',t:'Hastings',d:'I Normanni conquistano l\'Inghilterra e ne riscrivono lingua, leggi e nobiltà.'},
{a:1075,m:'s',t:'Il Dictatus papae',d:'Gregorio VII scrive che il papa può deporre l\'imperatore: comincia la lotta per le investiture.'},
{a:1122,m:'s',t:'Il concordato di Worms',d:'Un compromesso sulle investiture: il vescovo lo fa la Chiesa, le terre le dà il re.'},
{a:1176,m:'s',t:'Legnano',d:'I comuni lombardi battono Federico Barbarossa: le città hanno imparato a fare la guerra.'},
{a:1204,m:'s',t:'La quarta crociata saccheggia Costantinopoli',d:'I crociati depredano la città cristiana che dovevano difendere.'},
{a:1209,m:'s',t:'Francesco d\'Assisi',d:'La povertà scelta come critica vivente a una Chiesa ricca.'},
{a:1231,m:'s',t:'Le Costituzioni di Melfi',d:'Federico II costruisce il primo Stato accentrato d\'Europa: funzionari, non feudatari.'},
{a:1250,m:'f',t:'La disputa sugli universali',d:'I concetti generali esistono davvero o sono solo nomi? Duecento anni di battaglia.'},
{a:1266,m:'s',t:'Gli Angioini nel Sud',d:'Cade la casa sveva: il Mezzogiorno passa di mano e comincia a scivolare indietro.'},
{a:1271,m:'s',t:'Marco Polo parte',d:'Ventiquattro anni in Asia, e un libro che l\'Europa leggerà per secoli come una favola vera.'},
{a:1302,m:'s',t:'La bolla Unam Sanctam',d:'Bonifacio VIII rivendica ogni potere. Un anno dopo viene schiaffeggiato ad Anagni.'},
{a:1309,m:'s',t:'Il papato ad Avignone',d:'Settant\'anni sotto l\'influenza del re di Francia: il prestigio di Roma si consuma.'},
{a:1337,m:'s',t:'La guerra dei Cent\'anni',d:'Francia e Inghilterra si combattono per generazioni: ne escono due nazioni.'},
{a:1378,m:'s',t:'Il tumulto dei Ciompi',d:'A Firenze i lavoratori della lana chiedono di contare. Per sei settimane governano.'},
{a:1378,m:'s',t:'Il grande scisma d\'Occidente',d:'Due papi, poi tre. Chi obbedisce a chi? La Chiesa perde credibilità.'},
{a:1431,m:'s',t:'Giovanna d\'Arco al rogo',d:'Diciannove anni, contadina, condottiera. Bruciata per eresia, santa cinque secoli dopo.'},

/* ── Rinascimento e prima età moderna ──────────────────── */
{a:1454,m:'s',t:'La pace di Lodi',d:'Quarant\'anni di equilibrio fra gli Stati italiani. Finiranno male nel 1494.'},
{a:1469,m:'f',t:'L\'Accademia neoplatonica',d:'A Firenze Ficino traduce Platone: l\'uomo torna al centro come «grande miracolo».'},
{a:1486,m:'f',t:'Pico e la dignità dell\'uomo',d:'Non abbiamo natura fissa: siamo l\'unico essere che si dà la forma da sé.'},
{a:1494,m:'s',t:'Carlo VIII scende in Italia',d:'Comincia la stagione in cui la penisola è il campo di battaglia degli altri.'},
{a:1498,m:'s',t:'Vasco da Gama in India',d:'La via delle spezie per mare: il Mediterraneo smette di essere il centro del mondo.'},
{a:1521,m:'s',t:'La dieta di Worms',d:'«Non posso e non voglio ritrattare». Lutero davanti all\'imperatore.'},
{a:1524,m:'s',t:'La guerra dei contadini',d:'Centomila morti in Germania. Lutero sta con i principi: la Riforma non è rivoluzione sociale.'},
{a:1534,m:'s',t:'Enrico VIII capo della Chiesa',d:'Per un divorzio negato l\'Inghilterra esce da Roma.'},
{a:1541,m:'s',t:'Calvino a Ginevra',d:'Una città governata secondo la fede, e una dottrina che cambierà il rapporto col lavoro.'},
{a:1555,m:'s',t:'La pace di Augusta',d:'Ogni principe sceglie la religione dei suoi sudditi. Una tregua, non una libertà.'},
{a:1571,m:'s',t:'Lepanto',d:'L\'ultima grande battaglia di galee: l\'espansione ottomana nel Mediterraneo si arresta.'},
{a:1588,m:'s',t:'L\'Invincibile Armata',d:'La flotta spagnola affonda davanti all\'Inghilterra: comincia un passaggio di consegne.'},
{a:1598,m:'s',t:'L\'editto di Nantes',d:'La Francia concede ai protestanti di esistere. Sarà revocato novant\'anni dopo.'},
{a:1620,m:'f',t:'Il Novum Organum',d:'Bacone: la natura si comanda solo obbedendole. Prima si osserva, poi si generalizza.'},
{a:1633,m:'s',t:'L\'abiura di Galileo',d:'Costretto a rinnegare quello che aveva visto col cannocchiale.'},
{a:1642,m:'s',t:'La rivoluzione inglese',d:'Il parlamento contro il re. Sette anni dopo Carlo I sarà decapitato.'},
{a:1648,m:'f',t:'Il metodo di Cartesio in geometria',d:'Le curve diventano equazioni: due discipline separate si fondono in una.'},
{a:1677,m:'f',t:'L\'Etica di Spinoza',d:'Dio e natura sono la stessa cosa. Pubblicata dopo la morte, per prudenza.'},
{a:1687,m:'f',t:'Locke e la tolleranza',d:'Lo Stato si occupa dei beni terreni, non delle anime: separare è l\'unico modo di convivere.'},
{a:1688,m:'s',t:'La gloriosa rivoluzione',d:'Un re se ne va senza spargimento di sangue e il parlamento detta le condizioni.'},
{a:1714,m:'f',t:'Le monadi di Leibniz',d:'Infiniti punti di vista su uno stesso mondo, ciascuno che rispecchia tutti gli altri.'},
{a:1725,m:'f',t:'La Scienza nuova di Vico',d:'Conosciamo davvero solo ciò che facciamo: e la storia la facciamo noi.'},
{a:1748,m:'s',t:'Gli scavi di Pompei',d:'L\'antichità smette di essere un\'idea e diventa una cosa da dissotterrare.'},
{a:1755,m:'s',t:'Il terremoto di Lisbona',d:'Trentamila morti in un giorno di Ognissanti. L\'ottimismo settecentesco non si riprende.'},
{a:1764,m:'s',t:'Beccaria contro la pena di morte',d:'Dei delitti e delle pene: la pena serve a prevenire, non a vendicare.'},

/* ── Rivoluzioni e Ottocento ───────────────────────────── */
{a:1769,m:'s',t:'La macchina a vapore di Watt',d:'L\'energia smette di dipendere dal vento, dall\'acqua e dai muscoli.'},
{a:1789,m:'s',t:'La presa della Bastiglia',d:'Una prigione quasi vuota, ma il simbolo giusto: il 14 luglio diventa una data.'},
{a:1789,m:'s',t:'La Dichiarazione dei diritti',d:'Gli uomini nascono liberi e uguali nei diritti: scritto, non più solo pensato.'},
{a:1791,m:'s',t:'Olympe de Gouges',d:'Scrive la Dichiarazione dei diritti della donna. Sarà ghigliottinata.'},
{a:1793,m:'s',t:'Il Terrore',d:'La rivoluzione divora i suoi figli: sedicimila condanne in tredici mesi.'},
{a:1804,m:'s',t:'Il codice civile napoleonico',d:'Una legge uguale per tutti, scritta in modo che si possa leggere.'},
{a:1805,m:'s',t:'Trafalgar e Austerlitz',d:'Nello stesso anno Napoleone perde il mare e stravince sulla terra.'},
{a:1812,m:'s',t:'La campagna di Russia',d:'Seicentomila partono, cinquantamila tornano. L\'inizio della fine.'},
{a:1821,m:'s',t:'I moti del \'20-\'21',d:'Le società segrete chiedono costituzioni. Vengono schiacciate, ma qualcosa resta.'},
{a:1831,m:'s',t:'Mazzini fonda la Giovine Italia',d:'Non più congiure di pochi: educare un popolo a volersi nazione.'},
{a:1848,m:'s',t:'Le cinque giornate di Milano',d:'La città caccia gli austriaci a mani quasi nude. Torneranno in agosto.'},
{a:1849,m:'s',t:'La Repubblica Romana',d:'Mazzini, Garibaldi e una costituzione avanzatissima. Dura cinque mesi.'},
{a:1852,m:'s',t:'Cavour al governo',d:'Il Piemonte si moderniza e si cerca un\'alleanza che valga più di un esercito.'},
{a:1859,m:'s',t:'La seconda guerra d\'indipendenza',d:'Con la Francia contro l\'Austria: la Lombardia passa ai Savoia.'},
{a:1860,m:'s',t:'La spedizione dei Mille',d:'Mille volontari e un regno che si sfalda in sei mesi.'},
{a:1861,m:'s',t:'Il brigantaggio',d:'Il Sud non accetta il nuovo Stato: una guerra civile che nessuno chiama così.'},
{a:1866,m:'s',t:'Il Veneto all\'Italia',d:'Si perde a Custoza e a Lissa, e si vince lo stesso: la diplomazia conta più delle armi.'},
{a:1870,m:'s',t:'La breccia di Porta Pia',d:'Roma capitale. Il papa si dichiara prigioniero e per sessant\'anni i cattolici non voteranno.'},
{a:1876,m:'s',t:'La Sinistra storica al governo',d:'Scuola elementare obbligatoria, allargamento del voto, protezionismo.'},
{a:1882,m:'s',t:'La Triplice Alleanza',d:'L\'Italia si lega a Germania e Austria: all\'alleato di ieri e al nemico di sempre.'},
{a:1889,m:'s',t:'Il codice Zanardelli',d:'Abolita la pena di morte, riconosciuto il diritto di sciopero.'},
{a:1892,m:'s',t:'Nasce il partito socialista',d:'Gli operai smettono di essere solo una questione di ordine pubblico.'},
{a:1898,m:'s',t:'I moti di Milano',d:'Bava Beccaris spara sulla folla che chiede pane: ottanta morti.'},
{a:1900,m:'s',t:'Umberto I ucciso a Monza',d:'Un anarchico vendica il 1898. Sale al trono Vittorio Emanuele III.'},

/* ── Filosofia dell'Ottocento ──────────────────────────── */
{a:1794,m:'f',t:'Fichte e l\'Io che si pone',d:'Non c\'è oggetto senza soggetto: il mondo è il campo in cui l\'Io agisce.'},
{a:1800,m:'f',t:'Schelling e la natura vivente',d:'La natura non è materia inerte da usare: è spirito che dorme.'},
{a:1817,m:'f',t:'L\'Enciclopedia di Hegel',d:'Logica, natura, spirito: tutto il reale in un solo sistema che si muove.'},
{a:1830,m:'f',t:'Comte e i tre stadi',d:'Ogni sapere passa da spiegazioni divine ad astratte a scientifiche.'},
{a:1841,m:'f',t:'Feuerbach: Dio è l\'uomo',d:'Non è Dio ad aver fatto l\'uomo, ma l\'uomo ad aver proiettato se stesso in cielo.'},
{a:1844,m:'f',t:'I manoscritti sull\'alienazione',d:'Marx: chi lavora si estrania dal prodotto, dal gesto, da sé e dagli altri.'},
{a:1849,m:'f',t:'La malattia mortale',d:'Kierkegaard: la disperazione è un rapporto con sé che non si scioglie né si evita.'},
{a:1859,m:'f',t:'Mill e la libertà',d:'Si può limitare qualcuno solo per impedirgli di far male ad altri. Su di sé è sovrano.'},
{a:1862,m:'f',t:'Spencer e l\'evoluzione universale',d:'Dall\'omogeneo all\'eterogeneo: la stessa legge per gli astri, i corpi e le società.'},
{a:1872,m:'f',t:'La nascita della tragedia',d:'Nietzsche: i Greci reggevano l\'orrore mettendogli sopra una forma bella.'},
{a:1883,m:'f',t:'Così parlò Zarathustra',d:'Il cammello, il leone, il fanciullo: tre modi di stare davanti ai valori.'},
{a:1887,m:'f',t:'La genealogia della morale',d:'Da dove vengono i nostri «bene» e «male»? Da chi non poteva vendicarsi altrimenti.'},

/* ── Primo Novecento ───────────────────────────────────── */
{a:1902,m:'s',t:'La questione meridionale',d:'Salvemini e Nitti misurano il divario: due Italie dentro lo stesso Stato.'},
{a:1904,m:'s',t:'Il primo sciopero generale',d:'Quattro giorni di paese fermo: il conflitto sociale entra nella normalità.'},
{a:1911,m:'s',t:'La guerra di Libia',d:'L\'Italia si prende una colonia e ci trova sabbia e una guerriglia lunga vent\'anni.'},
{a:1912,m:'s',t:'Il suffragio universale maschile',d:'Da tre a otto milioni di elettori: la politica deve imparare a parlare a tutti.'},
{a:1915,m:'s',t:'L\'Italia entra in guerra',d:'Un patto segreto a Londra e un parlamento messo davanti al fatto compiuto.'},
{a:1916,m:'s',t:'Verdun e la Somme',d:'Due battaglie, un milione e mezzo di uomini fra morti e feriti, e il fronte fermo.'},
{a:1917,m:'s',t:'Caporetto',d:'L\'esercito italiano arretra di cento chilometri. Poi tiene sul Piave.'},
{a:1918,m:'s',t:'L\'influenza spagnola',d:'Cinquanta milioni di morti: più della guerra appena finita.'},
{a:1919,m:'s',t:'Il biennio rosso',d:'Occupazioni di fabbriche e di terre: la borghesia si spaventa e cerca protezione.'},
{a:1920,m:'s',t:'Il trattato di Sèvres',d:'L\'impero ottomano viene spartito: nascono i confini che ancora oggi non tengono.'},
{a:1924,m:'s',t:'Il delitto Matteotti',d:'Denuncia i brogli in parlamento e viene ucciso. Da lì il fascismo smette di fingere.'},
{a:1929,m:'s',t:'I Patti Lateranensi',d:'Stato e Chiesa fanno pace dopo sessant\'anni. Il fascismo ne esce legittimato.'},
{a:1931,m:'f',t:'Il teorema di Gödel',d:'In ogni sistema abbastanza ricco restano verità che il sistema non sa dimostrare.'},
{a:1935,m:'s',t:'L\'invasione dell\'Etiopia',d:'Gas contro civili e un impero proclamato. La Società delle Nazioni non ferma nulla.'},
{a:1938,m:'s',t:'Le leggi razziali',d:'Lo Stato italiano espelle i propri cittadini ebrei da scuole, uffici e professioni.'},
{a:1940,m:'s',t:'L\'Italia entra nella seconda guerra',d:'Impreparata, per sedersi al tavolo dei vincitori. Non ci arriverà.'},
{a:1943,m:'s',t:'L\'8 settembre',d:'L\'armistizio annunciato alla radio, il re in fuga, l\'esercito senza ordini.'},
{a:1944,m:'s',t:'Le Fosse Ardeatine',d:'Trecentotrentacinque civili uccisi per rappresaglia in un giorno.'},
{a:1945,m:'s',t:'La Liberazione',d:'Il 25 aprile le città del Nord insorgono prima dell\'arrivo degli Alleati.'},
{a:1945,m:'s',t:'Il processo di Norimberga',d:'Per la prima volta si giudica chi ha obbedito: gli ordini non bastano più come difesa.'},

/* ── Secondo Novecento ─────────────────────────────────── */
{a:1948,m:'s',t:'Nasce Israele',d:'E con esso una questione aperta che attraverserà tutto il secolo.'},
{a:1949,m:'s',t:'La Cina di Mao',d:'Un quarto dell\'umanità passa al comunismo.'},
{a:1950,m:'s',t:'La guerra di Corea',d:'La guerra fredda si scalda: tre milioni di morti e un confine che non si muove.'},
{a:1953,m:'s',t:'La struttura del DNA',d:'Watson, Crick e Franklin: l\'ereditarietà diventa una molecola che si può leggere.'},
{a:1956,m:'s',t:'I fatti d\'Ungheria',d:'I carri sovietici a Budapest. Molti comunisti occidentali stracciano la tessera.'},
{a:1957,m:'s',t:'Lo Sputnik',d:'Una sfera che fa bip nello spazio, e l\'Occidente si scopre indietro.'},
{a:1960,m:'s',t:'L\'anno dell\'Africa',d:'Diciassette paesi diventano indipendenti in dodici mesi.'},
{a:1962,m:'s',t:'La crisi dei missili a Cuba',d:'Tredici giorni in cui il mondo è stato più vicino alla fine di sempre.'},
{a:1963,m:'s',t:'I have a dream',d:'Duecentomila persone a Washington, e una frase che resta.'},
{a:1963,m:'s',t:'Il concilio Vaticano II',d:'La Chiesa parla la lingua di tutti i giorni e si rimette in ascolto del mondo.'},
{a:1967,m:'s',t:'Lettera a una professoressa',d:'Don Milani: la scuola boccia i poveri e chiama merito la fortuna di nascere bene.'},
{a:1968,m:'s',t:'La primavera di Praga',d:'Un socialismo dal volto umano, schiacciato dai carri in agosto.'},
{a:1969,m:'s',t:'L\'uomo sulla Luna',d:'Seicento milioni di persone guardano insieme la stessa cosa per la prima volta.'},
{a:1970,m:'s',t:'Lo Statuto dei lavoratori',d:'La Costituzione entra dentro la fabbrica: diritti anche dove si timbra il cartellino.'},
{a:1970,m:'s',t:'Il divorzio in Italia',d:'Approvato in parlamento e confermato dal referendum del 1974.'},
{a:1973,m:'s',t:'Il golpe in Cile',d:'Un governo eletto rovesciato l\'11 settembre. Diciassette anni di dittatura.'},
{a:1973,m:'s',t:'La crisi petrolifera',d:'Domeniche a piedi e la scoperta che l\'energia non è infinita né neutrale.'},
{a:1975,m:'s',t:'Il nuovo diritto di famiglia',d:'Cade il capofamiglia: marito e moglie hanno gli stessi diritti.'},
{a:1978,m:'s',t:'La legge Basaglia',d:'L\'Italia chiude i manicomi: primo paese al mondo a farlo.'},
{a:1980,m:'s',t:'La strage di Bologna',d:'Ottantacinque morti alla stazione, il 2 agosto, alle 10 e 25.'},
{a:1981,m:'s',t:'Il divorzio fra Tesoro e Banca d\'Italia',d:'Lo Stato non può più stampare moneta per pagarsi i debiti: il debito comincia a correre.'},
{a:1986,m:'s',t:'Chernobyl',d:'Una nube che non rispetta i confini: il rischio diventa per la prima volta globale.'},
{a:1989,m:'s',t:'Il web di Tim Berners-Lee',d:'Al CERN nasce il World Wide Web, e viene regalato al mondo.'},
{a:1992,m:'s',t:'Le stragi di Capaci e via d\'Amelio',d:'Falcone e Borsellino uccisi a due mesi di distanza. Lo Stato reagisce.'},
{a:1993,m:'s',t:'Il trattato di Maastricht',d:'Dalla comunità economica all\'Unione europea: nasce la cittadinanza europea.'},
{a:1994,m:'s',t:'Il genocidio in Ruanda',d:'Ottocentomila morti in cento giorni mentre il mondo guarda altrove.'},
{a:1995,m:'s',t:'Srebrenica',d:'Ottomila uomini uccisi in una zona protetta dall\'ONU.'},

/* ── Filosofia del Novecento ───────────────────────────── */
{a:1905,m:'f',t:'Weber e l\'etica protestante',d:'Il capitalismo nasce anche da una fede: lavorare come dovere, guadagnare senza godere.'},
{a:1912,m:'f',t:'Croce e la filosofia dello spirito',d:'Arte, logica, economia, etica: quattro forme distinte che non si annullano fra loro.'},
{a:1923,m:'f',t:'Lukács e la reificazione',d:'I rapporti fra persone prendono l\'aspetto di rapporti fra cose.'},
{a:1929,m:'f',t:'Gramsci comincia i Quaderni',d:'In carcere: il potere si tiene col consenso, e il consenso si costruisce con la cultura.'},
{a:1934,m:'f',t:'Popper e la falsificabilità',d:'Una teoria è scientifica se dice in anticipo che cosa la smentirebbe.'},
{a:1936,m:'f',t:'Benjamin e l\'opera d\'arte riprodotta',d:'La fotografia toglie l\'aura all\'originale e apre l\'arte alla politica.'},
{a:1938,m:'f',t:'Husserl e la crisi delle scienze',d:'La scienza ha dimenticato il mondo della vita da cui è nata.'},
{a:1947,m:'f',t:'Se questo è un uomo',d:'Levi scrive per testimoniare, e scopre che testimoniare è già una forma di pensiero.'},
{a:1949,m:'f',t:'Il secondo sesso',d:'Simone de Beauvoir: donna non si nasce, lo si diventa.'},
{a:1955,m:'f',t:'Eros e civiltà',d:'Marcuse: una parte della rinuncia che ci chiedono non serve alla civiltà, serve al potere.'},
{a:1960,m:'f',t:'Verità e metodo',d:'Gadamer: capire non è uscire dal proprio tempo, è farlo incontrare con quello del testo.'},
{a:1964,m:'f',t:'L\'uomo a una dimensione',d:'Marcuse: una società può essere totalitaria anche senza polizia, creando i bisogni.'},
{a:1971,m:'f',t:'Rawls e la teoria della giustizia',d:'Quali regole sceglieresti se non sapessi in che posizione ti tocca nascere?'},
{a:1979,m:'f',t:'Jonas e il principio responsabilità',d:'Agisci in modo che gli effetti di ciò che fai lascino ancora una vita possibile sulla terra.'},
{a:1979,m:'f',t:'Lyotard e la fine dei grandi racconti',d:'Non crediamo più alle storie che spiegavano tutto: progresso, emancipazione, salvezza.'},
{a:1981,m:'f',t:'Habermas e l\'agire comunicativo',d:'Non tutta la ragione è calcolo: c\'è anche quella che cerca l\'intesa.'},
{a:1998,m:'f',t:'Fede e ragione',d:'Giovanni Paolo II: le due ali con cui lo spirito umano si alza verso la verità.'}

);
