/* ══════════════════════════════════════════════════════════
   GLI EVENTI DELLA LINEA DEL TEMPO
   Ricavati dalle slide: un fatto per ogni snodo che in classe
   viene davvero raccontato. Ogni voce ha:
     a  = anno (negativo per gli anni prima di Cristo)
     m  = materia: 's' storia, 'f' filosofia
     t  = titolo, cioè come lo si chiama a lezione
     d  = una riga che dice perché conta
   L'ordine nel file non ha importanza: la pagina riordina.
   ══════════════════════════════════════════════════════════ */
const EVENTI = [

/* ── MONDO ANTICO ───────────────────────────────────────── */
{a:-3500,m:'s',t:'Nasce la scrittura in Mesopotamia',d:'Con i segni sull\'argilla comincia ciò che chiamiamo storia: prima di allora ci sono i fatti, non i documenti.'},
{a:-1750,m:'s',t:'Il codice di Hammurabi',d:'Le regole vengono incise sulla pietra: chi comanda non può più cambiarle a piacere ogni mattina.'},
{a:-753,m:'s',t:'Fondazione di Roma',d:'La data che i Romani stessi si daranno per cominciare a contare gli anni.'},
{a:-624,m:'f',t:'Talete di Mileto',d:'Per la prima volta qualcuno spiega il mondo senza chiamare in causa gli dèi: tutto viene dall\'acqua.'},
{a:-570,m:'f',t:'Pitagora e i numeri',d:'Se la realtà si lascia misurare, allora ha una struttura: il numero come chiave delle cose.'},
{a:-540,m:'f',t:'Eraclito: tutto scorre',d:'Nulla resta uguale a sé stesso. La guerra dei contrari è ciò che tiene insieme il mondo.'},
{a:-510,m:'s',t:'Roma diventa repubblica',d:'Cacciato il re, il potere si divide fra magistrature che durano un anno.'},
{a:-500,m:'f',t:'Parmenide: l\'essere è',d:'Il rovescio di Eraclito: se una cosa è, non può non essere. Nasce la logica.'},
{a:-490,m:'s',t:'Le guerre persiane',d:'Poche città greche fermano il più grande impero del mondo: da qui l\'idea che l\'Occidente sia altro dall\'Oriente.'},
{a:-450,m:'f',t:'I sofisti',d:'Insegnano a parlare bene a pagamento. Se ogni tesi ha la sua contraria, chi decide qual è vera?'},
{a:-399,m:'f',t:'La morte di Socrate',d:'Condannato dalla città che diceva di voler rendere migliore. Muore per non rinnegare il proprio metodo.'},
{a:-387,m:'f',t:'Platone apre l\'Accademia',d:'Le cose che vediamo sono copie: le idee stanno altrove e sono quelle vere.'},
{a:-335,m:'f',t:'Aristotele e il Liceo',d:'Riporta le idee dentro le cose e mette ordine in tutto lo scibile: logica, fisica, etica, politica.'},
{a:-323,m:'s',t:'Muore Alessandro Magno',d:'Il suo impero si spezza, ma la cultura greca resta padrona di tutto il Mediterraneo orientale.'},
{a:-306,m:'f',t:'Epicuro e il Giardino',d:'La filosofia come cura: togliere la paura degli dèi e della morte per vivere sereni.'},
{a:-300,m:'f',t:'Nasce lo stoicismo',d:'Non possiamo scegliere ciò che accade, solo come stargli davanti.'},
{a:-146,m:'s',t:'Roma distrugge Cartagine',d:'Il Mediterraneo diventa un lago romano.'},
{a:-44,m:'s',t:'L\'assassinio di Cesare',d:'La repubblica prova a difendersi da un uomo solo, e proprio così finisce.'},
{a:-27,m:'s',t:'Augusto e il principato',d:'Un potere personale con le forme della repubblica: durerà tre secoli.'},

/* ── TARDOANTICO E MEDIOEVO ─────────────────────────────── */
{a:313,m:'s',t:'Editto di Milano',d:'Il cristianesimo smette di essere perseguitato: in pochi decenni diventerà la religione dell\'impero.'},
{a:250,m:'f',t:'Plotino e il neoplatonismo',d:'Tutto discende da un Uno indicibile: la filosofia greca prende la forma che passerà al cristianesimo.'},
{a:397,m:'f',t:'Le Confessioni di Agostino',d:'La prima volta che un filosofo racconta sé stesso: il tempo, la memoria, la volontà divisa.'},
{a:476,m:'s',t:'Cade l\'impero d\'Occidente',d:'Non un crollo in un giorno: la fine di un\'organizzazione che non reggeva più.'},
{a:622,m:'s',t:'L\'Egira: nasce l\'islam',d:'In un secolo una nuova religione unifica dalla Spagna alla Persia.'},
{a:800,m:'s',t:'Carlo Magno imperatore',d:'L\'idea di impero torna in Occidente, e nasce il nodo fra potere del re e potere del papa.'},
{a:1000,m:'s',t:'La ripresa dell\'anno Mille',d:'Più cibo, più gente, più città: l\'Europa ricomincia a crescere.'},
{a:1077,m:'s',t:'Canossa',d:'L\'imperatore aspetta tre giorni nella neve: chi comanda davvero, il papa o il re?'},
{a:1095,m:'s',t:'La prima crociata',d:'In centomila partono per Gerusalemme. Fede, terra, mercato: le ragioni sono tutte insieme.'},
{a:1088,m:'s',t:'Nasce l\'università di Bologna',d:'Il sapere esce dai monasteri e si organizza in corporazioni di studenti e maestri.'},
{a:1215,m:'s',t:'La Magna Carta',d:'Anche il re deve rispondere a delle regole: il primo mattone del costituzionalismo.'},
{a:1265,m:'f',t:'Tommaso e la Summa',d:'Fede e ragione non si contraddicono: si può dimostrare con Aristotele ciò in cui si crede.'},
{a:1300,m:'f',t:'Ockham e il rasoio',d:'Non moltiplicare gli enti senza necessità: comincia lo smontaggio della metafisica medievale.'},
{a:1348,m:'s',t:'La peste nera',d:'Muore un europeo su tre. Chi resta vale di più: cambiano salari, campagne, mentalità.'},
{a:1453,m:'s',t:'Cade Costantinopoli',d:'Finisce l\'impero romano d\'Oriente e i dotti greci portano in Italia i loro libri.'},

/* ── ETÀ MODERNA ────────────────────────────────────────── */
{a:1440,m:'s',t:'La stampa di Gutenberg',d:'Le idee cominciano a viaggiare più veloci di chi le vieta.'},
{a:1492,m:'s',t:'Colombo arriva in America',d:'Due mondi che si ignoravano si toccano: comincia il primo scambio davvero globale.'},
{a:1513,m:'f',t:'Machiavelli scrive il Principe',d:'La politica si studia per quello che è, non per quello che dovrebbe essere.'},
{a:1517,m:'s',t:'Lutero e le 95 tesi',d:'La cristianità occidentale si spezza e nessuno riuscirà più a ricucirla.'},
{a:1543,m:'s',t:'Copernico: la Terra si muove',d:'Il pianeta perde il centro dell\'universo. Non è un dettaglio tecnico: è una ferita.'},
{a:1545,m:'s',t:'Il concilio di Trento',d:'La Chiesa di Roma si riorganizza: dogmi, seminari, indice dei libri proibiti.'},
{a:1600,m:'f',t:'Giordano Bruno al rogo',d:'Universo infinito e mondi innumerevoli: pagato con la vita in Campo de\' Fiori.'},
{a:1610,m:'f',t:'Galileo e il cannocchiale',d:'Guardare per decidere. La prova sperimentale prende il posto dell\'autorità del testo.'},
{a:1618,m:'s',t:'La guerra dei Trent\'anni',d:'Trent\'anni di guerra di religione lasciano la Germania devastata e l\'Europa laica per stanchezza.'},
{a:1637,m:'f',t:'Il Discorso sul metodo',d:'Cartesio dubita di tutto per trovare l\'unica cosa indubitabile: che sta dubitando.'},
{a:1648,m:'s',t:'La pace di Vestfalia',d:'Nasce l\'idea di Stato sovrano: dentro i suoi confini nessuno comanda al posto suo.'},
{a:1651,m:'f',t:'Il Leviatano di Hobbes',d:'Senza uno Stato che spaventi tutti, la vita è solitaria, povera, brutale e breve.'},
{a:1687,m:'s',t:'I Principia di Newton',d:'Una sola legge per la mela e per i pianeti: il cielo e la terra obbediscono alle stesse regole.'},
{a:1690,m:'f',t:'Locke e i due trattati',d:'Il potere nasce da un patto e può essere revocato: la base teorica delle rivoluzioni che verranno.'},
{a:1748,m:'f',t:'Montesquieu e i tre poteri',d:'Solo il potere può fermare il potere: dividerlo in tre è la garanzia della libertà.'},
{a:1751,m:'f',t:'L\'Encyclopédie',d:'Mettere tutto il sapere in ordine alfabetico e alla portata di chiunque sappia leggere.'},
{a:1762,m:'f',t:'Rousseau e il contratto sociale',d:'L\'uomo è nato libero e dovunque è in catene. La sovranità appartiene al popolo.'},
{a:1748,m:'f',t:'Hume e la critica della causa',d:'Che il sole sorgerà domani non è una certezza: è un\'abitudine.'},

/* ── OTTOCENTO ──────────────────────────────────────────── */
{a:1776,m:'s',t:'Indipendenza americana',d:'Per la prima volta un popolo si dà da sé una costituzione scritta.'},
{a:1781,m:'f',t:'La Critica della ragion pura',d:'Kant: non è la mente che si adegua alle cose, sono le cose che passano dalle forme della mente.'},
{a:1789,m:'s',t:'La Rivoluzione francese',d:'Cadono i privilegi di nascita. Libertà, uguaglianza e terrore nello stesso decennio.'},
{a:1785,m:'f',t:'La legge morale in noi',d:'Kant: agisci solo secondo quella regola che vorresti valesse per tutti.'},
{a:1799,m:'s',t:'Napoleone al potere',d:'Esporta i codici della rivoluzione a colpi di cannone, e si fa incoronare imperatore.'},
{a:1807,m:'f',t:'La Fenomenologia di Hegel',d:'La coscienza cresce attraverso i suoi conflitti: servo e signore hanno bisogno l\'uno dell\'altro.'},
{a:1815,m:'s',t:'Il congresso di Vienna',d:'I re rimettono a posto la carta d\'Europa fingendo che il 1789 non sia mai accaduto.'},
{a:1819,m:'f',t:'Schopenhauer: il mondo come volontà',d:'Dietro le cose non c\'è ragione ma una spinta cieca a vivere. Perciò si soffre.'},
{a:1830,m:'s',t:'La prima rivoluzione industriale',d:'Il vapore, la fabbrica, la città: in due generazioni cambia il modo di lavorare e di vivere.'},
{a:1843,m:'f',t:'Kierkegaard: aut-aut',d:'Non esiste una sintesi che concili tutto: bisogna scegliere, e la scelta angoscia.'},
{a:1848,m:'s',t:'La primavera dei popoli',d:'Mezza Europa insorge nello stesso anno. Quasi tutte le rivolte falliscono, nessuna passa senza lasciare traccia.'},
{a:1848,m:'f',t:'Il Manifesto di Marx ed Engels',d:'La storia di ogni società è storia di lotte di classi.'},
{a:1859,m:'s',t:'Darwin e l\'origine delle specie',d:'Le specie non sono create una volta per tutte: cambiano, e l\'uomo con loro.'},
{a:1861,m:'s',t:'L\'Unità d\'Italia',d:'Nasce uno Stato che deve ancora inventarsi gli italiani.'},
{a:1861,m:'s',t:'La guerra civile americana',d:'Si combatte sulla schiavitù e sul modello economico di un continente intero.'},
{a:1867,m:'f',t:'Il Capitale',d:'Marx smonta il meccanismo del profitto: il plusvalore è lavoro non pagato.'},
{a:1871,m:'s',t:'Nasce l\'impero tedesco',d:'Bismarck unifica la Germania con tre guerre: l\'equilibrio europeo non sarà più lo stesso.'},
{a:1882,m:'f',t:'Nietzsche: Dio è morto',d:'Non un annuncio ateo ma una diagnosi: è finita la fiducia in un fondamento che garantisca il senso.'},
{a:1885,m:'s',t:'La spartizione dell\'Africa',d:'Le potenze europee si dividono un continente attorno a un tavolo, a Berlino.'},
{a:1899,m:'f',t:'Freud e l\'interpretazione dei sogni',d:'L\'io non è padrone in casa propria: sotto la coscienza lavorano forze che non conosciamo.'},

/* ── NOVECENTO ──────────────────────────────────────────── */
{a:1900,m:'s',t:'La Belle Époque',d:'L\'Europa si crede al culmine del progresso, mentre prepara la sua guerra civile.'},
{a:1903,m:'s',t:'L\'Italia giolittiana',d:'Industria al Nord, emigrazione al Sud, e per la prima volta lo Stato tratta con i sindacati.'},
{a:1905,m:'s',t:'Einstein e la relatività',d:'Spazio e tempo smettono di essere il fondale immobile del mondo.'},
{a:1907,m:'f',t:'Bergson e la durata',d:'Il tempo vissuto non è quello dell\'orologio: dentro di noi i momenti si compenetrano.'},
{a:1913,m:'f',t:'Husserl e la fenomenologia',d:'Tornare alle cose stesse: descrivere come il mondo si dà alla coscienza, prima di spiegarlo.'},
{a:1914,m:'s',t:'Scoppia la Grande guerra',d:'Doveva finire per Natale. Durò quattro anni e uccise dieci milioni di soldati.'},
{a:1917,m:'s',t:'La rivoluzione russa',d:'Per la prima volta un partito marxista prende il potere in uno Stato.'},
{a:1919,m:'s',t:'Il trattato di Versailles',d:'Una pace che umilia i vinti e prepara il conflitto successivo.'},
{a:1921,m:'f',t:'Il Tractatus di Wittgenstein',d:'Su ciò di cui non si può parlare, si deve tacere.'},
{a:1922,m:'s',t:'La marcia su Roma',d:'In tre anni il fascismo passa dal governo alla dittatura.'},
{a:1927,m:'f',t:'Essere e tempo',d:'Heidegger: siamo gettati nel mondo e ci muoviamo verso la morte. L\'angoscia ci restituisce a noi stessi.'},
{a:1929,m:'s',t:'La crisi del \'29',d:'Da Wall Street la rovina arriva ovunque: milioni senza lavoro e la democrazia sotto accusa.'},
{a:1933,m:'s',t:'Hitler al potere',d:'Arriva con le elezioni e smonta la democrazia in pochi mesi, dall\'interno.'},
{a:1936,m:'s',t:'La guerra civile spagnola',d:'La prova generale della seconda guerra mondiale, combattuta da mezzo mondo.'},
{a:1939,m:'s',t:'La seconda guerra mondiale',d:'Sei anni, sessanta milioni di morti, e per la prima volta più civili che soldati.'},
{a:1942,m:'s',t:'La Shoah',d:'Lo sterminio pianificato di sei milioni di ebrei, organizzato come una procedura amministrativa.'},
{a:1944,m:'f',t:'Dialettica dell\'illuminismo',d:'Horkheimer e Adorno: la ragione che doveva liberarci si è rovesciata in dominio.'},
{a:1945,m:'s',t:'Hiroshima',d:'Con l\'atomica l\'umanità acquista per la prima volta il potere di finire.'},
{a:1946,m:'s',t:'L\'Italia sceglie la repubblica',d:'Il 2 giugno votano per la prima volta anche le donne.'},
{a:1948,m:'s',t:'La Costituzione italiana',d:'Uguaglianza, lavoro, pluralismo, ripudio della guerra: le regole nate dall\'antifascismo.'},
{a:1948,m:'s',t:'Dichiarazione dei diritti umani',d:'Dopo la guerra, il tentativo di scrivere ciò che nessuno Stato può fare a nessun essere umano.'},
{a:1947,m:'s',t:'Comincia la guerra fredda',d:'Due blocchi, due sistemi, un equilibrio tenuto in piedi dalla paura reciproca.'},
{a:1943,m:'f',t:'L\'essere e il nulla',d:'Sartre: l\'esistenza precede l\'essenza, siamo condannati a essere liberi.'},
{a:1951,m:'f',t:'Le origini del totalitarismo',d:'Arendt: ideologia più terrore. Il bersaglio non è l\'oppositore ma la capacità di cominciare qualcosa.'},
{a:1953,m:'f',t:'Le Ricerche filosofiche',d:'Il secondo Wittgenstein demolisce il primo: il significato di una parola è il suo uso.'},
{a:1957,m:'s',t:'I trattati di Roma',d:'Sei paesi che si erano appena massacrati decidono di mettere in comune il carbone e l\'acciaio.'},
{a:1958,m:'s',t:'Il miracolo economico italiano',d:'In dieci anni un paese agricolo diventa una potenza industriale.'},
{a:1958,m:'f',t:'Vita activa',d:'Arendt: lavoro, opera e azione. Solo agendo fra gli altri si mostra chi siamo.'},
{a:1961,m:'s',t:'Il muro di Berlino',d:'Una città tagliata in due per impedire alla gente di andarsene.'},
{a:1963,m:'f',t:'La banalità del male',d:'Arendt al processo Eichmann: per fare un male enorme può bastare smettere di pensare.'},
{a:1966,m:'f',t:'Le parole e le cose',d:'Foucault: l\'uomo come soggetto fondatore è un\'invenzione recente, e può finire.'},
{a:1968,m:'s',t:'Il Sessantotto',d:'Studenti e operai contestano insieme l\'autorità, la guerra e il modo di vivere dei padri.'},
{a:1969,m:'s',t:'Piazza Fontana',d:'Una bomba a Milano apre gli anni della strategia della tensione.'},
{a:1975,m:'f',t:'Sorvegliare e punire',d:'Foucault: il potere moderno non picchia, dispone gli sguardi. Chi si sente visto si controlla da sé.'},
{a:1978,m:'s',t:'Il caso Moro',d:'Cinquantacinque giorni di prigionia, e lo Stato che decide di non trattare.'},
{a:1989,m:'s',t:'Cade il muro di Berlino',d:'Un annuncio confuso in televisione manda in strada una città intera.'},
{a:1991,m:'s',t:'Finisce l\'Unione Sovietica',d:'Un impero si dissolve senza una guerra: la bandiera scende dal Cremlino il giorno di Natale.'},
{a:1992,m:'s',t:'Tangentopoli',d:'In due anni si sfalda l\'intero sistema dei partiti nato nel 1948.'},

/* ── OGGI ───────────────────────────────────────────────── */
{a:2001,m:'s',t:'L\'11 settembre',d:'La minaccia non è più uno Stato ma una rete senza territorio. Ne seguono due guerre lunghe vent\'anni.'},
{a:2002,m:'s',t:'L\'euro nelle tasche',d:'Dodici paesi rinunciano alla propria moneta senza avere una politica di bilancio comune.'},
{a:2008,m:'s',t:'La crisi finanziaria',d:'Prestiti concessi a chi non poteva restituirli travolgono le banche di mezzo mondo.'},
{a:2015,m:'s',t:'Gli accordi di Parigi',d:'Centonovantasei paesi si impegnano sul clima. Gli impegni presi non bastano.'},
{a:2016,m:'s',t:'Brexit e l\'ondata populista',d:'Chi si sente lasciato indietro dalla globalizzazione trova finalmente una voce politica.'},
{a:2020,m:'s',t:'La pandemia',d:'Il mondo si ferma insieme per la prima volta, e in un anno arriva un vaccino.'},
{a:2022,m:'s',t:'La guerra in Ucraina',d:'La più grande guerra in Europa dal 1945: l\'ordine nato nel 1991 non regge più.'}

];
